// src/lib/comments/CommentInbox.svelte
<script lang="ts">
 import type { CommentInboxProps, AdminComment, CommentStatus, BulkAction } from './types.ts';
 const props: CommentInboxProps = $props();
 let selected = $state(new Set<string>());
 let page = $state(0);
 let detail = $state<AdminComment|null>(null);
 let deleteId = $state<string|null>(null);
 let operationError = $state<unknown>(null);
 const labels:Record<CommentStatus,string>={pending:'Pending',approved:'Approved',spam:'Spam',trash:'Trash'};
 const empty:Record<CommentStatus,string>={pending:'No comments awaiting moderation.',approved:'No approved comments yet.',spam:'No spam comments.',trash:'Trash is empty.'};
 const pages=$derived(Math.max(1,Math.ceil(props.comments.length/20)));
 const rows=$derived(props.comments.slice(page*20,(page+1)*20));
 const all=$derived(rows.length>0&&rows.every(row=>selected.has(row.id)));
 $effect(()=>{props.activeStatus;props.collectionFilter;props.searchQuery;selected=new Set();page=0;});
 function toggle(id:string){const next=new Set(selected);if(next.has(id))next.delete(id);else next.add(id);selected=next;}
 function toggleAll(){const next=new Set(selected);for(const row of rows){if(all)next.delete(row.id);else next.add(row.id);}selected=next;}
 async function bulk(action:BulkAction){if(selected.size===0)return;try{await props.onBulkAction([...selected],action);selected=new Set();operationError=null;}catch(error){operationError=error;}}
 async function status(id:string,value:CommentStatus){detail=null;try{await props.onCommentStatusChange(id,value);selected=new Set();operationError=null;}catch(error){operationError=error;}}
 function askDelete(id:string){deleteId=id;detail=null;operationError=null;props.onDeleteErrorReset();}
 function closeDelete(){deleteId=null;operationError=null;props.onDeleteErrorReset();}
 async function remove(){if(!deleteId)return;try{await props.onCommentDelete(deleteId);deleteId=null;operationError=null;}catch(error){operationError=error;}}
 function describeError(error:unknown){return error instanceof Error?error.message:typeof error==='string'?error:'The operation could not be completed.';}
 function escape(event:KeyboardEvent){if(event.key==='Escape'&&!event.defaultPrevented){if(detail){event.preventDefault();detail=null;}else if(deleteId){event.preventDefault();closeDelete();}}}
</script>
<svelte:document onkeydown={escape}/>
<section aria-label="Comments" class="inbox">
 <header><h1>Comments</h1><p>Review and moderate comments across your content.</p></header>
 <div role="tablist" aria-label="Comment status" class="tabs">
  {#each Object.entries(labels) as [value,label]}
   <button type="button" role="tab" aria-selected={props.activeStatus===value} onclick={()=>props.onStatusChange(value as CommentStatus)}>
    <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18"><path d={value==='approved'?'m5 12 4 4 10-10':value==='pending'?'M12 4v8l5 3':value==='spam'?'M12 6v8m0 3v1':'M6 7h12m-10 0v13h8V7m-6-3h4'} fill="none" stroke="currentColor" stroke-width="2"/></svg>
    {label}{#if value!=='approved'&&props.counts[value as CommentStatus]>0}<span>{props.counts[value as CommentStatus]}</span>{/if}
   </button>
  {/each}
 </div>
 <div class="filters"><input type="search" aria-label="Search comments" placeholder="Search comments..." value={props.searchQuery} oninput={event=>props.onSearchChange(event.currentTarget.value)}/>
  {#if Object.keys(props.collections).length>1}<select aria-label="Filter by collection" value={props.collectionFilter} onchange={event=>props.onCollectionFilterChange(event.currentTarget.value)}><option value="">All collections</option>{#each Object.entries(props.collections) as [slug,collection]}<option value={slug}>{collection.label}</option>{/each}</select>{/if}
 </div>
 {#if selected.size>0}<div class="bulk"><strong>{selected.size} selected</strong><div>
  {#if props.activeStatus!=='approved'}<button onclick={()=>bulk('approve')}>Approve</button>{/if}
  {#if props.activeStatus!=='spam'}<button onclick={()=>bulk('spam')}>Spam</button>{/if}
  {#if props.activeStatus!=='trash'}<button onclick={()=>bulk('trash')}>Trash</button>{/if}
  {#if props.isAdmin}<button class="danger" onclick={()=>bulk('delete')}>Delete</button>{/if}
 </div></div>{/if}
 {#if operationError&&!deleteId}<p role="alert">{describeError(operationError)}</p>{/if}
 {#if props.isLoading&&props.comments.length===0}<p class="empty">Loading comments...</p>
 {:else if rows.length===0}<div class="empty"><p>{props.searchQuery||props.collectionFilter?'No comments match your filters.':empty[props.activeStatus]}</p><p>{props.searchQuery||props.collectionFilter?'Try a different search or collection filter.':'Comments with this status will appear here.'}</p></div>
 {:else}<div class="table-wrap"><table><thead><tr><th scope="col"><input type="checkbox" aria-label="Select all" checked={all} onchange={toggleAll}/></th><th scope="col">Author</th><th scope="col">Comment</th><th scope="col">Content</th><th scope="col">Date</th><th scope="col">Actions</th></tr></thead><tbody>
  {#each rows as comment (comment.id)}<tr class:selected={selected.has(comment.id)}>
   <td><input type="checkbox" aria-label={`Select comment by ${comment.authorName}`} checked={selected.has(comment.id)} onchange={()=>toggle(comment.id)}/></td>
   <td><button class="text" onclick={()=>detail=comment}><strong>{comment.authorName}</strong><small>{comment.authorEmail}</small></button></td>
   <td><button class="text" onclick={()=>detail=comment}>{comment.body.length>120?comment.body.slice(0,120)+'...':comment.body}</button></td>
   <td>{comment.collection}</td><td>{new Date(comment.createdAt).toLocaleDateString()}</td>
   <td><div class="actions">{#if comment.status!=='approved'}<button aria-label="Approve" disabled={props.isStatusPending} onclick={()=>status(comment.id,'approved')}>✓</button>{/if}{#if comment.status!=='spam'}<button aria-label="Mark as spam" disabled={props.isStatusPending} onclick={()=>status(comment.id,'spam')}>!</button>{/if}{#if comment.status!=='trash'}<button aria-label="Trash" disabled={props.isStatusPending} onclick={()=>status(comment.id,'trash')}>⌫</button>{/if}{#if props.isAdmin}<button aria-label="Delete permanently" class="danger" disabled={props.isStatusPending} onclick={()=>askDelete(comment.id)}>×</button>{/if}</div></td>
  </tr>{/each}
 </tbody></table></div>{/if}
 {#if pages>1||props.nextCursor}<footer><span>{props.comments.length} {props.comments.length===1?'comment':'comments'}</span><div><button aria-label="Previous page" disabled={page===0} onclick={()=>page--}>←</button><span>{page+1} / {pages}</span><button aria-label="Next page" disabled={page>=pages-1&&!props.nextCursor} onclick={()=>{if(page>=pages-1&&props.nextCursor)props.onLoadMore();page++;}}>→</button></div></footer>{/if}
</section>
{#if detail}<div class="overlay" role="presentation" onclick={event=>{if(event.target===event.currentTarget)detail=null;}} onkeydown={escape}><div class="detail" role="dialog" tabindex="-1" aria-modal="true" aria-labelledby="comment-detail-title"><header><h2 id="comment-detail-title">Comment Detail</h2><button aria-label="Close" onclick={()=>detail=null}>×</button></header><p>{detail.status} · {new Date(detail.createdAt).toLocaleString()}</p><h3>Author</h3><p>{detail.authorName}{#if detail.authorUserId} · Registered user{/if}</p><p>{detail.authorEmail}</p><h3>Comment</h3><p class="body">{detail.body}</p><h3>Content</h3><p>Collection: {detail.collection}</p><p>Content ID: {detail.contentId}</p>{#if detail.parentId}<p>Reply to: {detail.parentId}</p>{/if}{#if detail.moderationMetadata&&Object.keys(detail.moderationMetadata).length}<h3>Moderation Signals</h3><pre>{JSON.stringify(detail.moderationMetadata,null,2)}</pre>{/if}<div class="actions">{#if detail.status!=='approved'}<button disabled={props.isStatusPending} onclick={()=>status(detail!.id,'approved')}>Approve</button>{/if}{#if detail.status!=='spam'}<button disabled={props.isStatusPending} onclick={()=>status(detail!.id,'spam')}>Spam</button>{/if}{#if detail.status!=='trash'}<button disabled={props.isStatusPending} onclick={()=>status(detail!.id,'trash')}>Trash</button>{/if}{#if props.isAdmin}<button disabled={props.isStatusPending} class="danger" onclick={()=>askDelete(detail!.id)}>Delete Permanently</button>{/if}</div></div></div>{/if}
{#if deleteId}<div class="overlay"><div class="confirm" role="dialog" tabindex="-1" aria-modal="true" aria-labelledby="delete-comment-title"><h2 id="delete-comment-title">Delete Comment?</h2><p>This will permanently delete this comment. This action cannot be undone.</p>{#if props.deleteError||operationError}<p role="alert">{describeError(props.deleteError||operationError)}</p>{/if}<div class="actions"><button disabled={props.isStatusPending} onclick={closeDelete}>Cancel</button><button disabled={props.isStatusPending} class="danger" onclick={remove}>{props.isStatusPending?'Deleting...':'Delete'}</button></div></div></div>{/if}
<style>
 .inbox{display:grid;gap:1.25rem;color:var(--foreground,#17212e)}h1,h2,h3,p{margin:0}header p,.empty,small{color:var(--muted-foreground,#667085)}header p{margin-top:.45rem}.tabs,.filters,.actions,.bulk,.bulk>div,footer,footer>div{display:flex;align-items:center;gap:.5rem}.tabs{border-bottom:1px solid #d7dde5;flex-wrap:wrap}.tabs button{display:flex;gap:.4rem;align-items:center;border:0;border-bottom:2px solid transparent;border-radius:0}.tabs button[aria-selected=true]{border-color:#3b66cf;color:#315bbd}.tabs span{background:#e8edf5;border-radius:1rem;padding:.1rem .4rem}.filters input{flex:1}.bulk{justify-content:space-between;background:#f4f6fa;padding:.75rem;border-radius:.5rem}button,input,select{font:inherit}button{padding:.45rem .7rem;background:white;border:1px solid #d7dde5;border-radius:.35rem;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:hover:enabled{background:#f2f5fa}.text{display:block;text-align:start;border:0;background:none;padding:0}.text small{display:block;margin-top:.25rem}.danger{color:#a21c2e}.table-wrap{overflow:auto;border:1px solid #d7dde5;border-radius:.5rem}table{border-collapse:collapse;width:100%;text-align:start}td,th{padding:.8rem;border-bottom:1px solid #e4e8ed}th{text-align:start;font-weight:600;background:#f6f8fb}tr.selected{background:#edf3ff}.empty{text-align:center;padding:2.5rem}.empty p+p{margin-top:.5rem}footer{justify-content:space-between}.overlay{position:fixed;inset:0;background:#0005;z-index:40;display:flex;align-items:center;justify-content:center}.detail,.confirm{background:white;padding:1.5rem;border-radius:.6rem;box-shadow:0 8px 30px #0003;max-height:90vh;overflow:auto}.detail{margin-inline-start:auto;height:100%;width:min(32rem,100%);border-radius:0;display:grid;gap:1rem}.detail header{display:flex;justify-content:space-between;align-items:center}.confirm{max-width:28rem;display:grid;gap:1rem}.body{white-space:pre-wrap;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere}.confirm .actions{justify-content:flex-end}input[type=search],select{padding:.5rem;border:1px solid #d7dde5;border-radius:.35rem}
</style>

// parity/emdash/entry-locks/source/packages/admin/src/components/comments/CommentInbox.tsx
/**
 * Comment moderation inbox.
 *
 * Status tabs (Pending, Approved, Spam, Trash), search, collection filter,
 * table with row actions, bulk selection, and detail slide-over.
 */

import { Badge, Button, Checkbox, Select } from "@cloudflare/kumo";
import { plural } from "@lingui/core/macro";
import { useLingui } from "@lingui/react/macro";
import {
	Check,
	CheckCircle,
	ClockCountdown,
	ShieldWarning,
	Trash,
	Warning,
} from "@phosphor-icons/react";
import * as React from "react";

import type {
	AdminComment,
	CommentCounts,
	CommentStatus,
	BulkAction,
} from "../../lib/api/comments.js";
import { cn } from "../../lib/utils.js";
import { ADMIN_NAV_ICONS } from "../admin-navigation-icons.js";
import { CaretNext, CaretPrev } from "../ArrowIcons.js";
import { ConfirmDialog } from "../ConfirmDialog.js";
import { PageHeader } from "../PageHeader.js";
import { TableToolbarSearch } from "../TableToolbar.js";
import { CommentDetail } from "./CommentDetail.js";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface CommentInboxProps {
	comments: AdminComment[];
	counts: CommentCounts;
	isLoading: boolean;
	nextCursor?: string;
	collections: Record<string, { label: string }>;
	activeStatus: CommentStatus;
	onStatusChange: (status: CommentStatus) => void;
	collectionFilter: string;
	onCollectionFilterChange: (collection: string) => void;
	searchQuery: string;
	onSearchChange: (query: string) => void;
	onCommentStatusChange: (id: string, status: CommentStatus) => Promise<unknown>;
	onCommentDelete: (id: string) => Promise<unknown>;
	onBulkAction: (ids: string[], action: BulkAction) => Promise<unknown>;
	onLoadMore: () => void;
	isAdmin: boolean;
	isStatusPending: boolean;
	deleteError: unknown;
	onDeleteErrorReset: () => void;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

const PAGE_SIZE = 20;
const STATUS_TAB_CLASS_NAME = "flex-1 justify-center text-xs sm:flex-none sm:text-sm";
const STATUS_TAB_ICON_CLASS_NAME = "size-3.5 shrink-0 sm:size-4";
const STATUS_TAB_LABEL_CLASS_NAME = "flex items-center gap-1 sm:gap-1.5";
const STATUS_TAB_RENDER = (
	<button
		type="button"
		style={{ paddingInline: "clamp(0.1875rem, calc(10vw - 1.8125rem), 0.625rem)" }}
	/>
);

export function CommentInbox({
	comments,
	counts,
	isLoading,
	nextCursor,
	collections,
	activeStatus,
	onStatusChange,
	collectionFilter,
	onCollectionFilterChange,
	searchQuery,
	onSearchChange,
	onCommentStatusChange,
	onCommentDelete,
	onBulkAction,
	onLoadMore,
	isAdmin,
	isStatusPending,
	deleteError,
	onDeleteErrorReset,
}: CommentInboxProps) {
	const { t } = useLingui();

	// Selection state
	const [selected, setSelected] = React.useState<Set<string>>(new Set());
	const [detailComment, setDetailComment] = React.useState<AdminComment | null>(null);
	const [deleteId, setDeleteId] = React.useState<string | null>(null);

	// Pagination (client-side within loaded data)
	const [page, setPage] = React.useState(0);

	// Reset selection and page when status tab or filters change
	React.useEffect(() => {
		setSelected(new Set());
		setPage(0);
	}, [activeStatus, collectionFilter, searchQuery]);

	const clearSelection = React.useCallback(() => setSelected(new Set()), []);

	const totalPages = Math.max(1, Math.ceil(comments.length / PAGE_SIZE));
	const paginatedComments = comments.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);

	// Bulk select
	const allOnPageSelected =
		paginatedComments.length > 0 && paginatedComments.every((c) => selected.has(c.id));

	const toggleAll = () => {
		setSelected((prev) => {
			const next = new Set(prev);
			if (allOnPageSelected) {
				for (const c of paginatedComments) next.delete(c.id);
			} else {
				for (const c of paginatedComments) next.add(c.id);
			}
			return next;
		});
	};

	const toggleOne = (id: string) => {
		setSelected((prev) => {
			const next = new Set(prev);
			if (next.has(id)) {
				next.delete(id);
			} else {
				next.add(id);
			}
			return next;
		});
	};

	const handleBulk = (action: BulkAction) => {
		if (selected.size === 0) return;
		void onBulkAction([...selected], action).then(clearSelection);
	};

	// Collection filter items
	const collectionItems: Record<string, string> = { "": t`All collections` };
	for (const [slug, config] of Object.entries(collections)) {
		collectionItems[slug] = config.label;
	}

	const searchPlaceholder = t`Search comments...`;

	return (
		<div className="space-y-6">
			<PageHeader
				title={t`Comments`}
				description={t`Review and moderate comments across your content.`}
				value={activeStatus}
				onValueChange={(v) => {
					if (v === "pending" || v === "approved" || v === "spam" || v === "trash") {
						onStatusChange(v);
					}
				}}
				tools={
					<>
						<TableToolbarSearch
							size="base"
							placeholder={searchPlaceholder}
							aria-label={t`Search comments`}
							value={searchQuery}
							onChange={(e) => onSearchChange(e.target.value)}
						/>
						{Object.keys(collections).length > 1 && (
							<Select
								className="w-full sm:w-auto"
								value={collectionFilter}
								onValueChange={(v) => onCollectionFilterChange(v ?? "")}
								items={collectionItems}
								aria-label={t`Filter by collection`}
							/>
						)}
					</>
				}
				tabs={[
					{
						value: "pending",
						className: STATUS_TAB_CLASS_NAME,
						render: STATUS_TAB_RENDER,
						label: (
							<span className={STATUS_TAB_LABEL_CLASS_NAME}>
								<ClockCountdown
									className={STATUS_TAB_ICON_CLASS_NAME}
									weight={activeStatus === "pending" ? "fill" : "regular"}
									aria-hidden="true"
								/>
								{t`Pending`}
								{counts.pending > 0 && <Badge variant="secondary">{counts.pending}</Badge>}
							</span>
						),
					},
					{
						value: "approved",
						className: STATUS_TAB_CLASS_NAME,
						render: STATUS_TAB_RENDER,
						label: (
							<span className={STATUS_TAB_LABEL_CLASS_NAME}>
								<CheckCircle
									className={STATUS_TAB_ICON_CLASS_NAME}
									weight={activeStatus === "approved" ? "fill" : "regular"}
									aria-hidden="true"
								/>
								{t`Approved`}
							</span>
						),
					},
					{
						value: "spam",
						className: STATUS_TAB_CLASS_NAME,
						render: STATUS_TAB_RENDER,
						label: (
							<span className={STATUS_TAB_LABEL_CLASS_NAME}>
								<ShieldWarning
									className={STATUS_TAB_ICON_CLASS_NAME}
									weight={activeStatus === "spam" ? "fill" : "regular"}
									aria-hidden="true"
								/>
								{t`Spam`}
								{counts.spam > 0 && <Badge variant="secondary">{counts.spam}</Badge>}
							</span>
						),
					},
					{
						value: "trash",
						className: STATUS_TAB_CLASS_NAME,
						render: STATUS_TAB_RENDER,
						label: (
							<span className={STATUS_TAB_LABEL_CLASS_NAME}>
								<Trash
									className={STATUS_TAB_ICON_CLASS_NAME}
									weight={activeStatus === "trash" ? "fill" : "regular"}
									aria-hidden="true"
								/>
								{t`Trash`}
								{counts.trash > 0 && <Badge variant="secondary">{counts.trash}</Badge>}
							</span>
						),
					},
				]}
			/>

			{/* Bulk action bar */}
			{selected.size > 0 && (
				<div className="flex items-center gap-3 rounded-lg border bg-kumo-tint/50 px-4 py-2">
					<span className="text-sm font-medium">
						{plural(selected.size, { one: "# selected", other: "# selected" })}
					</span>
					<div className="flex gap-2 ms-auto">
						{activeStatus !== "approved" && (
							<Button
								size="sm"
								icon={<Check className="h-3.5 w-3.5" />}
								onClick={() => handleBulk("approve")}
							>
								{t`Approve`}
							</Button>
						)}
						{activeStatus !== "spam" && (
							<Button
								size="sm"
								variant="outline"
								icon={<Warning className="h-3.5 w-3.5" />}
								onClick={() => handleBulk("spam")}
							>
								{t`Spam`}
							</Button>
						)}
						{activeStatus !== "trash" && (
							<Button
								size="sm"
								variant="outline"
								icon={<Trash className="h-3.5 w-3.5" />}
								onClick={() => handleBulk("trash")}
							>
								{t`Trash`}
							</Button>
						)}
						{isAdmin && (
							<Button
								size="sm"
								variant="destructive"
								icon={<Trash className="h-3.5 w-3.5" />}
								onClick={() => handleBulk("delete")}
							>
								{t`Delete`}
							</Button>
						)}
					</div>
				</div>
			)}

			{/* Table */}
			{isLoading && comments.length === 0 ? (
				<div className="py-12 text-center text-kumo-subtle">{t`Loading comments...`}</div>
			) : paginatedComments.length === 0 ? (
				<EmptyState status={activeStatus} hasFilters={Boolean(searchQuery || collectionFilter)} />
			) : (
				<div className="overflow-x-auto rounded-lg border bg-kumo-base">
					<table className="w-full">
						<thead>
							<tr className="border-b bg-kumo-tint/50">
								<th scope="col" className="w-10 px-3 py-3">
									<Checkbox
										checked={allOnPageSelected}
										onCheckedChange={toggleAll}
										aria-label={t`Select all`}
									/>
								</th>
								<th scope="col" className="px-4 py-3 text-start text-sm font-medium">
									{t`Author`}
								</th>
								<th scope="col" className="px-4 py-3 text-start text-sm font-medium">
									{t`Comment`}
								</th>
								<th scope="col" className="px-4 py-3 text-start text-sm font-medium">
									{t`Content`}
								</th>
								<th scope="col" className="px-4 py-3 text-start text-sm font-medium">
									{t`Date`}
								</th>
								<th scope="col" className="px-4 py-3 text-end text-sm font-medium">
									{t`Actions`}
								</th>
							</tr>
						</thead>
						<tbody className="divide-y divide-kumo-line">
							{paginatedComments.map((comment) => (
								<CommentRow
									key={comment.id}
									comment={comment}
									isSelected={selected.has(comment.id)}
									onToggle={() => toggleOne(comment.id)}
									onRowClick={() => setDetailComment(comment)}
									onStatusChange={(id, status) => {
										void onCommentStatusChange(id, status).then(clearSelection);
									}}
									onDelete={(id) => {
										setDeleteId(id);
										onDeleteErrorReset();
									}}
									isAdmin={isAdmin}
									isStatusPending={isStatusPending}
								/>
							))}
						</tbody>
					</table>
				</div>
			)}

			{/* Pagination */}
			{(totalPages > 1 || nextCursor) && (
				<div className="flex items-center justify-between">
					<span className="text-sm text-kumo-subtle">
						{plural(comments.length, { one: "# comment", other: "# comments" })}
					</span>
					<div className="flex items-center gap-2">
						<Button
							variant="outline"
							shape="square"
							disabled={page === 0}
							onClick={() => setPage(page - 1)}
							aria-label={t`Previous page`}
						>
							<CaretPrev className="h-4 w-4" />
						</Button>
						<span className="text-sm">
							{page + 1} / {totalPages}
						</span>
						<Button
							variant="outline"
							shape="square"
							disabled={page >= totalPages - 1 && !nextCursor}
							onClick={() => {
								if (page >= totalPages - 1 && nextCursor) {
									onLoadMore();
									setPage(page + 1);
								} else {
									setPage(page + 1);
								}
							}}
							aria-label={t`Next page`}
						>
							<CaretNext className="h-4 w-4" />
						</Button>
					</div>
				</div>
			)}

			{/* Detail slide-over */}
			{detailComment && (
				<CommentDetail
					comment={detailComment}
					onClose={() => setDetailComment(null)}
					onStatusChange={(id, status) => {
						void onCommentStatusChange(id, status).then(clearSelection);
						setDetailComment(null);
					}}
					onDelete={(id) => {
						setDeleteId(id);
						onDeleteErrorReset();
						setDetailComment(null);
					}}
					isAdmin={isAdmin}
					isStatusPending={isStatusPending}
				/>
			)}

			{/* Delete confirmation */}
			<ConfirmDialog
				open={!!deleteId}
				onClose={() => {
					setDeleteId(null);
					onDeleteErrorReset();
				}}
				title={t`Delete Comment?`}
				description={t`This will permanently delete this comment. This action cannot be undone.`}
				confirmLabel={t`Delete`}
				pendingLabel={t`Deleting...`}
				isPending={isStatusPending}
				error={deleteError}
				onConfirm={() => {
					if (deleteId) {
						void onCommentDelete(deleteId).then(() => setDeleteId(null));
					}
				}}
			/>
		</div>
	);
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

interface CommentRowProps {
	comment: AdminComment;
	isSelected: boolean;
	onToggle: () => void;
	onRowClick: () => void;
	onStatusChange: (id: string, status: CommentStatus) => void;
	onDelete: (id: string) => void;
	isAdmin: boolean;
	isStatusPending: boolean;
}

function CommentRow({
	comment,
	isSelected,
	onToggle,
	onRowClick,
	onStatusChange,
	onDelete,
	isAdmin,
	isStatusPending,
}: CommentRowProps) {
	const { t } = useLingui();
	const date = new Date(comment.createdAt);
	const excerpt = comment.body.length > 120 ? comment.body.slice(0, 120) + "..." : comment.body;

	return (
		<tr className={cn("hover:bg-kumo-tint/25", isSelected && "bg-kumo-tint/40")}>
			<td className="w-10 px-3 py-3">
				<Checkbox
					checked={isSelected}
					onCheckedChange={onToggle}
					aria-label={t`Select comment by ${comment.authorName}`}
				/>
			</td>
			<td className="px-4 py-3">
				<button type="button" onClick={onRowClick} className="text-start">
					<div className="font-medium text-sm">{comment.authorName}</div>
					<div className="text-xs text-kumo-subtle">{comment.authorEmail}</div>
				</button>
			</td>
			<td className="px-4 py-3 max-w-xs">
				<button
					type="button"
					onClick={onRowClick}
					className="text-start text-sm text-kumo-subtle hover:text-kumo-default line-clamp-2"
				>
					{excerpt}
				</button>
			</td>
			<td className="px-4 py-3">
				<div className="text-xs">
					<span className="font-medium">{comment.collection}</span>
				</div>
			</td>
			<td className="px-4 py-3 text-sm text-kumo-subtle whitespace-nowrap">
				{date.toLocaleDateString()}
			</td>
			<td className="px-4 py-3 text-end">
				<div className="flex items-center justify-end gap-1">
					{comment.status !== "approved" && (
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							aria-label={t`Approve`}
							onClick={() => onStatusChange(comment.id, "approved")}
							disabled={isStatusPending}
						>
							<Check className="h-4 w-4 text-kumo-success" />
						</Button>
					)}
					{comment.status !== "spam" && (
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							aria-label={t`Mark as spam`}
							onClick={() => onStatusChange(comment.id, "spam")}
							disabled={isStatusPending}
						>
							<Warning className="h-4 w-4 text-kumo-warning" />
						</Button>
					)}
					{comment.status !== "trash" && (
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							aria-label={t`Trash`}
							onClick={() => onStatusChange(comment.id, "trash")}
							disabled={isStatusPending}
						>
							<Trash className="h-4 w-4 text-kumo-subtle" />
						</Button>
					)}
					{isAdmin && (
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							aria-label={t`Delete permanently`}
							onClick={() => onDelete(comment.id)}
							disabled={isStatusPending}
						>
							<Trash className="h-4 w-4 text-kumo-danger" />
						</Button>
					)}
				</div>
			</td>
		</tr>
	);
}

function EmptyState({ status, hasFilters }: { status: CommentStatus; hasFilters: boolean }) {
	const { t } = useLingui();

	const messages: Record<CommentStatus, string> = {
		pending: t`No comments awaiting moderation.`,
		approved: t`No approved comments yet.`,
		spam: t`No spam comments.`,
		trash: t`Trash is empty.`,
	};

	return (
		<div className="py-10 text-center text-kumo-subtle">
			<ADMIN_NAV_ICONS.comments size={40} className="mx-auto mb-3 opacity-30" />
			<p className="text-base font-medium">
				{hasFilters ? t`No comments match your filters.` : messages[status]}
			</p>
			<p className="mt-1 text-sm">
				{hasFilters
					? t`Try a different search or collection filter.`
					: t`Comments with this status will appear here.`}
			</p>
		</div>
	);
}
