// src/lib/ui/BlocksField.svelte
<script lang="ts">
  // Native transport of the complete pinned BlocksField state transitions;
  // source: EmDash 913cb1bb admin/components/BlocksField.tsx, MIT Cloudflare Inc.
  import type {Snippet} from 'svelte';
  import type {BlockType,BlockFieldDefinition} from '$lib/server/schema/block-types';
  import {createBlockKey,createBlockValue,duplicateBlockValue,isStoredBlockValue,moveBlockValue,updateBlockFieldValue,type StoredBlockValue} from '$lib/blocks/state';
  import BlockSubField from './BlockSubField.svelte';
  export interface NestedFieldInput {name:string;field:{id:string;kind:string;label:string;required?:boolean;validation?:Record<string,unknown>;options?:unknown};value:unknown;onChange:(value:unknown)=>void}
  let {id,fieldPath,label,value,onchange,blockTypes,allowedTypes,retiredTypes,minItems=0,maxItems=100,readOnly=false,renderField}:{
    id:string;fieldPath:string;label:string;value:unknown;onchange:(value:StoredBlockValue[])=>void;blockTypes:readonly BlockType[];allowedTypes:readonly string[];retiredTypes:readonly string[];minItems?:number;maxItems?:number;readOnly?:boolean;renderField?:Snippet<[NestedFieldInput]>;
  }=$props();
  let pickerOpen=$state(false),query=$state(''),collapsed=$state(new Set<string>()),keyboardKey=$state<string|undefined>(),pointerKey=$state<string|undefined>();
  const blocks=$derived(Array.isArray(value)?value.filter(isStoredBlockValue):[]);
  const typeBySlug=$derived(new Map(blockTypes.map(type=>[type.slug,type])));
  const allowed=$derived(allowedTypes.map(slug=>typeBySlug.get(slug)).filter((type):type is BlockType=>type!==undefined).filter(type=>{const needle=query.trim().toLocaleLowerCase();return !needle||type.label.toLocaleLowerCase().includes(needle)||type.slug.toLocaleLowerCase().includes(needle)||Boolean(type.category?.toLocaleLowerCase().includes(needle));}));
  const grouped=$derived.by(()=>{const result=new Map<string,BlockType[]>();for(const type of allowed){const category=type.category||'Other';result.set(category,[...(result.get(category)??[]),type]);}return result;});
  function toggle(key:string){const next=new Set(collapsed);if(next.has(key))next.delete(key);else next.add(key);collapsed=next;}
  function duplicate(index:number,block:StoredBlockValue){const next=[...blocks];next.splice(index+1,0,duplicateBlockValue(block,createBlockKey()));onchange(next);}
  function move(key:string,to:number){onchange(moveBlockValue(blocks,blocks.findIndex(block=>block._key===key),to));}
  function keyboard(event:KeyboardEvent,key:string){
    if(event.code==='Space'){event.preventDefault();keyboardKey=keyboardKey===key?undefined:key;}
    else if(keyboardKey===key&&(event.key==='ArrowDown'||event.key==='ArrowUp')){event.preventDefault();move(key,blocks.findIndex(block=>block._key===key)+(event.key==='ArrowDown'?1:-1));}
    else if(event.key==='Escape')keyboardKey=undefined;
  }
  function summary(block:StoredBlockValue,fields:readonly BlockFieldDefinition[]){for(const field of fields){const value=block[field.slug];if(typeof value==='string'&&value.trim())return value.trim();}return null;}
  function nested(block:StoredBlockValue,field:BlockFieldDefinition):NestedFieldInput{
    return {name:`${fieldPath}.${block._key}.${field.slug}`,field:{id:`${id}:${block._key}:${field.slug}`,kind:field.type==='text'?'richText':field.type==='integer'?'number':field.type,label:field.label,required:field.required,validation:field.validation as Record<string,unknown>,options:Array.isArray(field.validation?.options)?field.validation.options.map(option=>({value:option,label:option})):field.options},value:block[field.slug],onChange:next=>onchange(updateBlockFieldValue(blocks,block._key,field.slug,next))};
  }
</script>
<div {id} class="blocks-field">
  <header><strong>{label}</strong>{#if !readOnly}<button type="button" disabled={blocks.length>=maxItems||allowed.length===0} onclick={()=>pickerOpen=!pickerOpen}>Add block</button>{/if}</header>
  {#if pickerOpen&&!readOnly}<div class="picker">
    <input aria-label="Search block types" placeholder="Search blocks" bind:value={query}/>
    {#each Array.from(grouped) as [category,types]}<p>{category}</p>{#each types as type(type.slug)}
      <button type="button" aria-label={type.label+(type.description??'')} onclick={()=>{onchange([...blocks,createBlockValue(type,createBlockKey())]);pickerOpen=false;query='';}}><strong>{type.label}</strong>{#if type.description}<span>{type.description}</span>{/if}</button>
    {/each}{/each}
    {#if allowed.length===0}<p>No matching block types</p>{/if}
  </div>{/if}
  {#if blocks.length===0}<p>No blocks yet</p>{/if}
  {#each blocks as block,index(block._key)}
    {@const type=typeBySlug.get(block._type)}
    {@const version=type?.versions.find(candidate=>candidate.version===block._version)}
    {@const unsupported=!type||!version||Boolean(version.unsupportedTypes?.length)}
    {@const retired=retiredTypes.includes(block._type)}
    {@const blockSummary=version?summary(block,version.fields):null}
    <section data-block-key={block._key} class:dragging={keyboardKey===block._key||pointerKey===block._key}>
      <header>
        {#if !readOnly}<button type="button" aria-label={`Reorder ${type?.label??block._type}`} aria-pressed={keyboardKey===block._key} onkeydown={event=>keyboard(event,block._key)}
          draggable="true" ondragstart={event=>{pointerKey=block._key;event.dataTransfer?.setData('text/plain',block._key);}} ondragend={()=>pointerKey=undefined} ondragover={event=>event.preventDefault()} ondrop={event=>{event.preventDefault();if(pointerKey)move(pointerKey,index);pointerKey=undefined;}}>⠿</button>{/if}
        <button type="button" aria-label={collapsed.has(block._key)?'Expand block':'Collapse block'} onclick={()=>toggle(block._key)}>
          <svg viewBox="0 0 20 20" width="16" height="16" class={collapsed.has(block._key)?'rtl:-scale-x-100':''} aria-hidden="true"><path d={collapsed.has(block._key)?'M7 4l6 6-6 6':'M4 7l6 6 6-6'} fill="none" stroke="currentColor"/></svg>
        </button>
        <strong>{type?.label??block._type}</strong><span>Version {block._version}</span>
        {#if type&&block._version!==type.currentVersion}<span>Inactive version</span>{/if}
        {#if retired}<span>Retired</span>{/if}{#if unsupported}<span>Unsupported</span>{/if}
        {#if !readOnly}<button type="button" aria-label="Duplicate block" disabled={retired||unsupported} onclick={()=>duplicate(index,block)}>Duplicate</button><button type="button" aria-label="Delete block" onclick={()=>onchange(blocks.filter(item=>item._key!==block._key))}>Delete</button>{/if}
      </header>
      {#if blockSummary}<p class="summary">{blockSummary}</p>{/if}
      {#if !collapsed.has(block._key)}<div class="fields">
        {#if unsupported}<p>This block cannot be edited because its stored definition is unavailable.</p>
        {:else}{#each version?.fields??[] as field(field.slug)}
          {#if renderField}{@render renderField(nested(block,field))}
          {:else}<BlockSubField id={`field-${fieldPath}.${block._key}.${field.slug}`} {field} value={block[field.slug]} {readOnly} onchange={next=>onchange(updateBlockFieldValue(blocks,block._key,field.slug,next))}/>{/if}
        {/each}{/if}
        <span class="sr-only">Block {index+1}</span>
      </div>{/if}
    </section>
  {/each}
  {#if blocks.length<minItems}<p role="alert">Add at least {minItems} blocks.</p>{/if}
</div>
<style>.blocks-field{display:grid;gap:12px}header{display:flex;flex-wrap:wrap;align-items:center;gap:8px}section,.picker{border:1px solid #c4cedd;border-radius:8px;padding:12px}.fields{display:grid;gap:16px;border-block-start:1px solid #d9e0eb;margin-block-start:12px;padding-block-start:12px}.summary{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.picker button span{display:block}.dragging{opacity:.5}.sr-only{position:absolute;inline-size:1px;block-size:1px;overflow:hidden;clip-path:inset(50%)}:global([dir=rtl] .rtl\:-scale-x-100){transform:scaleX(-1)}</style>

// parity/emdash/entry-locks/source/packages/admin/src/components/BlocksField.tsx
import { Badge, Button, Input, Label } from "@cloudflare/kumo";
import {
	closestCenter,
	DndContext,
	KeyboardSensor,
	PointerSensor,
	type DragEndEvent,
	useSensor,
	useSensors,
} from "@dnd-kit/core";
import {
	SortableContext,
	sortableKeyboardCoordinates,
	useSortable,
	verticalListSortingStrategy,
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useLingui } from "@lingui/react/macro";
import { CaretDown, CaretRight, Copy, DotsSixVertical, Plus, Trash } from "@phosphor-icons/react";
import * as React from "react";

import type { BlockFieldDefinition, BlockType } from "../lib/api/schema.js";
import {
	createBlockKey,
	createBlockValue,
	duplicateBlockValue,
	isStoredBlockValue,
	moveBlockValue,
	type StoredBlockValue,
	updateBlockFieldValue,
} from "../lib/block-field-state.js";
import { cn } from "../lib/utils.js";

interface NestedFieldDescriptor {
	id?: string;
	kind: string;
	label?: string;
	required?: boolean;
	options?: Array<{ value: string; label: string }> | Record<string, unknown>;
	validation?: Record<string, unknown>;
}

interface NestedFieldRenderInput {
	name: string;
	field: NestedFieldDescriptor;
	value: unknown;
	onChange: (value: unknown) => void;
}

export interface BlocksFieldProps {
	id: string;
	fieldPath: string;
	label: string;
	value: unknown;
	onChange: (value: StoredBlockValue[]) => void;
	blockTypes: readonly BlockType[];
	allowedTypes: readonly string[];
	retiredTypes: readonly string[];
	minItems?: number;
	maxItems?: number;
	readOnly?: boolean;
	renderField: (input: NestedFieldRenderInput) => React.ReactNode;
}

const NESTED_KIND: Record<string, string> = {
	string: "string",
	text: "richText",
	url: "url",
	number: "number",
	integer: "number",
	boolean: "boolean",
	datetime: "datetime",
	select: "select",
	multiSelect: "multiSelect",
	portableText: "portableText",
	image: "image",
	file: "file",
	repeater: "repeater",
};

function nestedDescriptor(
	outerId: string,
	blockKey: string,
	field: BlockFieldDefinition,
): NestedFieldDescriptor {
	const options = Array.isArray(field.validation?.options)
		? field.validation.options
				.filter((option): option is string => typeof option === "string")
				.map((option) => ({ value: option, label: option }))
		: field.options;
	return {
		id: `${outerId}:${blockKey}:${field.slug}`,
		kind: NESTED_KIND[field.type] ?? "unsupported",
		label: field.label,
		required: field.required,
		validation: field.validation,
		options,
	};
}

function summary(block: StoredBlockValue, fields: readonly BlockFieldDefinition[]): string | null {
	for (const field of fields) {
		const value = block[field.slug];
		if (typeof value === "string" && value.trim()) return value.trim();
	}
	return null;
}

export function BlocksField({
	id,
	fieldPath,
	label,
	value,
	onChange,
	blockTypes,
	allowedTypes,
	retiredTypes,
	minItems = 0,
	maxItems = 100,
	readOnly = false,
	renderField,
}: BlocksFieldProps) {
	const { t } = useLingui();
	const blocks = Array.isArray(value) ? value.filter(isStoredBlockValue) : [];
	const [pickerOpen, setPickerOpen] = React.useState(false);
	const [query, setQuery] = React.useState("");
	const [collapsed, setCollapsed] = React.useState<Set<string>>(() => new Set());
	const typeBySlug = React.useMemo(
		() => new Map(blockTypes.map((blockType) => [blockType.slug, blockType])),
		[blockTypes],
	);
	const allowed = allowedTypes
		.map((slug) => typeBySlug.get(slug))
		.filter((blockType): blockType is BlockType => blockType !== undefined)
		.filter((blockType) => {
			const needle = query.trim().toLocaleLowerCase();
			return (
				!needle ||
				blockType.label.toLocaleLowerCase().includes(needle) ||
				blockType.slug.toLocaleLowerCase().includes(needle) ||
				blockType.category?.toLocaleLowerCase().includes(needle)
			);
		});
	const grouped = new Map<string, BlockType[]>();
	for (const blockType of allowed) {
		const category = blockType.category || t`Other`;
		grouped.set(category, [...(grouped.get(category) ?? []), blockType]);
	}
	const sensors = useSensors(
		useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
		useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }),
	);

	const handleDragEnd = (event: DragEndEvent) => {
		if (!event.over || event.active.id === event.over.id) return;
		const from = blocks.findIndex((block) => block._key === event.active.id);
		const to = blocks.findIndex((block) => block._key === event.over?.id);
		onChange(moveBlockValue(blocks, from, to));
	};

	return (
		<div id={id} className="grid gap-3">
			<div className="flex items-center justify-between gap-3">
				<Label>{label}</Label>
				{!readOnly && (
					<Button
						variant="outline"
						size="sm"
						icon={<Plus />}
						disabled={blocks.length >= maxItems || allowed.length === 0}
						onClick={() => setPickerOpen((open) => !open)}
					>
						{t`Add block`}
					</Button>
				)}
			</div>

			{pickerOpen && !readOnly && (
				<div className="rounded-lg border border-kumo-line bg-kumo-control p-3 space-y-3">
					<Input
						aria-label={t`Search block types`}
						value={query}
						onChange={(event) => setQuery(event.target.value)}
						placeholder={t`Search blocks`}
					/>
					<div className="max-h-64 overflow-y-auto space-y-3">
						{Array.from(grouped, ([category, types]) => (
							<div key={category}>
								<p className="mb-1 text-xs font-medium text-kumo-subtle">{category}</p>
								<div className="grid gap-1 sm:grid-cols-2">
									{types.map((blockType) => (
										<Button
											key={blockType.slug}
											variant="ghost"
											className="h-auto justify-start text-start"
											onClick={() => {
												onChange([...blocks, createBlockValue(blockType, createBlockKey())]);
												setPickerOpen(false);
												setQuery("");
											}}
										>
											<span>
												<span className="block font-medium">{blockType.label}</span>
												{blockType.description && (
													<span className="block text-xs text-kumo-subtle">
														{blockType.description}
													</span>
												)}
											</span>
										</Button>
									))}
								</div>
							</div>
						))}
						{allowed.length === 0 && (
							<p className="py-4 text-center text-sm text-kumo-subtle">
								{t`No matching block types`}
							</p>
						)}
					</div>
				</div>
			)}

			{blocks.length === 0 ? (
				<p className="rounded-lg border border-dashed border-kumo-line p-6 text-center text-sm text-kumo-subtle">
					{t`No blocks yet`}
				</p>
			) : (
				<DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
					<SortableContext
						items={blocks.map((block) => block._key)}
						strategy={verticalListSortingStrategy}
					>
						<div className="space-y-3">
							{blocks.map((block, index) => (
								<BlockCard
									key={block._key}
									outerId={id}
									fieldPath={fieldPath}
									block={block}
									index={index}
									blockType={typeBySlug.get(block._type)}
									retired={retiredTypes.includes(block._type)}
									collapsed={collapsed.has(block._key)}
									readOnly={readOnly}
									onToggle={() =>
										setCollapsed((current) => {
											const next = new Set(current);
											if (next.has(block._key)) next.delete(block._key);
											else next.add(block._key);
											return next;
										})
									}
									onChange={(field, nextValue) =>
										onChange(updateBlockFieldValue(blocks, block._key, field, nextValue))
									}
									onDuplicate={() => {
										const next = [...blocks];
										next.splice(index + 1, 0, duplicateBlockValue(block, createBlockKey()));
										onChange(next);
									}}
									onDelete={() => onChange(blocks.filter((item) => item._key !== block._key))}
									renderField={renderField}
								/>
							))}
						</div>
					</SortableContext>
				</DndContext>
			)}

			{blocks.length < minItems && (
				<p className="text-sm text-kumo-danger">{t`Add at least ${minItems} blocks.`}</p>
			)}
		</div>
	);
}

interface BlockCardProps {
	outerId: string;
	fieldPath: string;
	block: StoredBlockValue;
	index: number;
	blockType?: BlockType;
	retired: boolean;
	collapsed: boolean;
	readOnly: boolean;
	onToggle: () => void;
	onChange: (field: string, value: unknown) => void;
	onDuplicate: () => void;
	onDelete: () => void;
	renderField: BlocksFieldProps["renderField"];
}

function BlockCard({
	outerId,
	fieldPath,
	block,
	index,
	blockType,
	retired,
	collapsed,
	readOnly,
	onToggle,
	onChange,
	onDuplicate,
	onDelete,
	renderField,
}: BlockCardProps) {
	const { t } = useLingui();
	const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
		id: block._key,
		disabled: readOnly,
	});
	const style = { transform: CSS.Transform.toString(transform), transition };
	const version = blockType?.versions.find((candidate) => candidate.version === block._version);
	const unsupported = !blockType || !version || Boolean(version.unsupportedTypes?.length);
	const inactive = Boolean(blockType && block._version !== blockType.currentVersion);
	const blockSummary = version ? summary(block, version.fields) : null;

	return (
		<section
			ref={setNodeRef}
			style={style}
			className={cn(
				"rounded-lg border border-kumo-line bg-kumo-control",
				isDragging && "opacity-50",
			)}
			data-block-key={block._key}
		>
			<div className="flex items-center gap-2 p-3">
				{!readOnly && (
					<button
						{...attributes}
						{...listeners}
						type="button"
						className="cursor-grab touch-none active:cursor-grabbing"
						aria-label={t`Reorder ${blockType?.label ?? block._type}`}
					>
						<DotsSixVertical className="h-5 w-5 text-kumo-subtle" />
					</button>
				)}
				<Button
					variant="ghost"
					shape="square"
					size="sm"
					onClick={onToggle}
					aria-label={collapsed ? t`Expand block` : t`Collapse block`}
				>
					{collapsed ? (
						<CaretRight className="h-4 w-4 rtl:-scale-x-100" />
					) : (
						<CaretDown className="h-4 w-4" />
					)}
				</Button>
				<div className="min-w-0 flex-1">
					<div className="flex flex-wrap items-center gap-2">
						<span className="font-medium">{blockType?.label ?? block._type}</span>
						<Badge variant="secondary">{t`Version ${block._version}`}</Badge>
						{inactive && <Badge variant="secondary">{t`Inactive version`}</Badge>}
						{retired && <Badge variant="secondary">{t`Retired`}</Badge>}
						{unsupported && <Badge variant="secondary">{t`Unsupported`}</Badge>}
					</div>
					{blockSummary && <p className="truncate text-xs text-kumo-subtle">{blockSummary}</p>}
				</div>
				{!readOnly && (
					<div className="flex items-center gap-1">
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							disabled={retired || unsupported}
							onClick={onDuplicate}
							aria-label={t`Duplicate block`}
						>
							<Copy className="h-4 w-4" />
						</Button>
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							onClick={onDelete}
							aria-label={t`Delete block`}
						>
							<Trash className="h-4 w-4 text-kumo-danger" />
						</Button>
					</div>
				)}
			</div>

			{!collapsed && (
				<div className="space-y-4 border-t border-kumo-line p-4">
					{unsupported ? (
						<p className="text-sm text-kumo-subtle">
							{t`This block cannot be edited because its stored definition is unavailable.`}
						</p>
					) : (
						version?.fields.map((field) =>
							renderField({
								name: `${fieldPath}.${block._key}.${field.slug}`,
								field: nestedDescriptor(outerId, block._key, field),
								value: block[field.slug],
								onChange: (nextValue) => onChange(field.slug, nextValue),
							}),
						)
					)}
					<span className="sr-only">{t`Block ${index + 1}`}</span>
				</div>
			)}
		</section>
	);
}
