// src/lib/menus/MenuList.svelte
<script lang="ts">
  // Native Svelte rendering of pinned MenuList/MenuCard behavior; MIT attribution
  // and framework substitutions are recorded in docs/menus.md.
  // Copyright 2026 Cloudflare Inc. MIT; see notices/emdash-MIT.txt.
  import * as api from './client.ts';
  import type { Menu, MenuClient } from './types.ts';
  let { client = api, basePath = '', locale, locales = [], mutationsEnabled = true, navigate = (url: string) => { location.href = url; } }:
    { client?: MenuClient; basePath?: string; locale?: string; locales?: string[]; mutationsEnabled?: boolean; navigate?: (url:string)=>void } = $props();
  let menus = $state<Menu[]>([]), loading = $state(true), error = $state('');
  let createOpen = $state(false), createPending = $state(false), createError = $state('');
  let deleteName = $state<string | null>(null), deletePending = $state(false), deleteError = $state('');
  const key = $props.id();
  async function load() { loading = true; error = ''; try { menus = await client.fetchMenus({ locale }); } catch (caught) { error = caught instanceof Error ? caught.message : 'Failed to fetch menus'; } finally { loading = false; } }
  $effect(() => { locale; void load(); });
  function changeCreate(open: boolean) { createOpen = open; if (!createPending) createError = ''; }
  async function create(event: SubmitEvent) {
    event.preventDefault(); if (createPending) return;
    const data = new FormData(event.currentTarget as HTMLFormElement); createPending = true; createError = '';
    try { const menu = await client.createMenu({ name: String(data.get('name') ?? ''), label: String(data.get('label') ?? ''), locale });
      createOpen = false; void load(); navigate(`${basePath}/menus/${menu.name}?locale=${encodeURIComponent(menu.locale)}`);
    } catch (caught) { createError = caught instanceof Error ? caught.message : 'Failed to create menu'; }
    finally { createPending = false; }
  }
  async function remove() { if (!deleteName || deletePending) return; deletePending = true; deleteError = '';
    try { await client.deleteMenu(deleteName, { locale }); deleteName = null; await load(); }
    catch (caught) { deleteError = caught instanceof Error ? caught.message : 'Failed to delete menu'; } finally { deletePending = false; }
  }
</script>

<header><div><h1>Menus</h1><p>Manage navigation menus for your site</p></div>
  {#if locales.length > 1}<label for={`${key}-locale`}>Locale</label><select id={`${key}-locale`} bind:value={locale}>{#each locales as option}<option value={option}>{option.toUpperCase()}</option>{/each}</select>{/if}
  <button disabled={!mutationsEnabled} onclick={() => changeCreate(true)}>Create Menu</button>
</header>
{#if loading}<p>Loading menus...</p>{:else if error}<p role="alert">{error}</p>
{:else if menus.length === 0}<section class="empty"><h2>No menus yet</h2><p>Create your first navigation menu to get started</p><button disabled={!mutationsEnabled} onclick={() => changeCreate(true)}>Create Menu</button></section>
{:else}<ul class="menus">{#each menus as menu (menu.id)}<li><article><h2>{menu.label}</h2><p>{menu.name}</p><p>{menu.itemCount ?? 0} {(menu.itemCount ?? 0) === 1 ? 'item' : 'items'}</p>
  {#if locales.length > 1}<p>{menu.locale.toUpperCase()}</p>{/if}
  <a href={`${basePath}/menus/${menu.name}?locale=${encodeURIComponent(menu.locale)}`}>Edit</a>
  <button disabled={!mutationsEnabled} aria-label={`Delete ${menu.name} menu`} onclick={() => { deleteName = menu.name; deleteError = ''; }}>Delete</button>
</article></li>{/each}</ul>{/if}
{#if createOpen}<div class="overlay"><div role="dialog" tabindex="-1" aria-modal="true" aria-labelledby={`${key}-create`}>
  <h2 id={`${key}-create`}>Create menu</h2><button type="button" aria-label="Close" onclick={() => changeCreate(false)}>×</button>
  <form onsubmit={create}><label for={`${key}-label`}>Label</label><input id={`${key}-label`} name="label" required placeholder="Primary navigation" />
    <p>Shown in the admin menu list.</p><label for={`${key}-name`}>Name</label><input id={`${key}-name`} name="name" required pattern="[a-z0-9\-]+" title="Only lowercase letters, numbers, and hyphens" placeholder="primary" />
    <p>Stable identifier for your site, such as primary or footer.</p>{#if createError}<p role="alert">{createError}</p>{/if}
    <footer><button type="button" onclick={() => changeCreate(false)}>Cancel</button><button type="submit" disabled={createPending}>{createPending ? 'Creating...' : 'Create'}</button></footer>
  </form>
</div></div>{/if}
{#if deleteName}<div class="overlay"><div role="dialog" tabindex="-1" aria-modal="true" aria-labelledby={`${key}-delete`}>
  <h2 id={`${key}-delete`}>Delete menu</h2><p>Are you sure you want to delete this menu? This will also delete all menu items. This action cannot be undone.</p>
  {#if deleteError}<p role="alert">{deleteError}</p>{/if}<footer><button onclick={() => { deleteName = null; deleteError = ''; }}>Cancel</button><button disabled={deletePending} onclick={remove}>{deletePending ? 'Deleting...' : 'Delete'}</button></footer>
</div></div>{/if}

<style>
  header,footer { display:flex; gap:1rem; align-items:center; justify-content:space-between; } .menus { list-style:none; padding:0; display:grid; grid-template-columns:repeat(auto-fit,minmax(16rem,1fr)); gap:1rem; }
  article,.empty { border:1px solid #d4d4d8; border-radius:.7rem; padding:1.25rem; } article a { margin-inline-end:1rem; } .overlay { position:fixed; inset:0; z-index:40; display:grid; place-items:center; background:#0006; padding:1rem; }
  [role=dialog] { background:white; color:#18181b; padding:1.5rem; border-radius:.75rem; width:min(32rem,100%); max-height:90dvh; overflow:auto; } form { display:grid; gap:.5rem; } input { padding:.6rem; border:1px solid #a1a1aa; border-radius:.35rem; } button { cursor:pointer; padding:.5rem .8rem; } button:disabled { cursor:default; opacity:.55; } [role=alert] { color:#b91c1c; }
</style>

// parity/emdash/entry-locks/source/packages/admin/src/components/MenuList.tsx
/**
 * Menu List component
 *
 * Displays all menus with ability to create, edit, and delete.
 */

import { Button, Dialog, Input, LayerCard, Toast } from "@cloudflare/kumo";
import { useLingui } from "@lingui/react/macro";
import { Plus, X } from "@phosphor-icons/react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import * as React from "react";

import { fetchMenus, createMenu, deleteMenu } from "../lib/api";
import { fetchManifest } from "../lib/api/client.js";
import { ADMIN_NAV_ICONS } from "./admin-navigation-icons.js";
import { ConfirmDialog } from "./ConfirmDialog.js";
import { DialogError, getMutationError } from "./DialogError.js";
import { LocaleSwitcher, useI18nConfig } from "./LocaleSwitcher.js";
import { MenuCard } from "./MenuCard.js";

export function MenuList() {
	const { t } = useLingui();
	const queryClient = useQueryClient();
	const navigate = useNavigate();
	const toastManager = Toast.useToastManager();
	const [isCreateOpen, setIsCreateOpen] = React.useState(false);
	const [deleteMenuName, setDeleteMenuName] = React.useState<string | null>(null);

	const { data: manifest } = useQuery({
		queryKey: ["manifest"],
		queryFn: fetchManifest,
	});
	const i18n = useI18nConfig(manifest);
	const [activeLocale, setActiveLocale] = React.useState<string | undefined>(undefined);
	React.useEffect(() => {
		if (i18n && !activeLocale) setActiveLocale(i18n.defaultLocale);
	}, [i18n, activeLocale]);

	const { data: menus, isLoading } = useQuery({
		queryKey: ["menus", activeLocale],
		queryFn: () => fetchMenus({ locale: activeLocale }),
	});

	const createMutation = useMutation({
		mutationFn: createMenu,
		onSuccess: (menu) => {
			void queryClient.invalidateQueries({ queryKey: ["menus"] });
			setIsCreateOpen(false);
			toastManager.add({
				title: t`Menu created`,
				description: t`Menu "${menu.label}" has been created.`,
			});
			void navigate({
				to: "/menus/$name",
				params: { name: menu.name },
				search: { locale: menu.locale },
			});
		},
	});

	const deleteMutation = useMutation({
		mutationFn: (name: string) => deleteMenu(name, { locale: activeLocale }),
		onSuccess: () => {
			void queryClient.invalidateQueries({ queryKey: ["menus"] });
			setDeleteMenuName(null);
			toastManager.add({
				title: t`Menu deleted`,
				description: t`The menu has been deleted.`,
			});
		},
	});

	const handleCreateOpenChange = (open: boolean) => {
		setIsCreateOpen(open);
		if (!createMutation.isPending) createMutation.reset();
	};

	const handleCreate = (e: React.FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		const formData = new FormData(e.currentTarget);
		const nameVal = formData.get("name");
		const name = typeof nameVal === "string" ? nameVal : "";
		const labelVal = formData.get("label");
		const label = typeof labelVal === "string" ? labelVal : "";
		createMutation.mutate({ name, label, locale: activeLocale });
	};

	if (isLoading) {
		return (
			<div className="flex items-center justify-center h-64">
				<div className="text-kumo-subtle">{t`Loading menus...`}</div>
			</div>
		);
	}

	return (
		<div className="space-y-6">
			<header className="flex flex-col gap-4 border-b border-kumo-line pb-4 sm:flex-row sm:items-start sm:justify-between">
				<div className="min-w-0">
					<h1 className="text-2xl font-semibold leading-tight">{t`Menus`}</h1>
					<p className="mt-1 text-sm leading-5 text-pretty text-kumo-subtle">
						{t`Manage navigation menus for your site`}
					</p>
				</div>
				<div className="flex flex-wrap items-center gap-2">
					{i18n && activeLocale ? (
						<LocaleSwitcher
							locales={i18n.locales}
							defaultLocale={i18n.defaultLocale}
							value={activeLocale}
							onChange={setActiveLocale}
						/>
					) : null}
					<Dialog.Root open={isCreateOpen} onOpenChange={handleCreateOpenChange}>
						<Dialog.Trigger
							render={(props) => (
								<Button {...props} icon={<Plus aria-hidden="true" />}>
									{t`Create Menu`}
								</Button>
							)}
						/>
						<Dialog
							className="flex max-h-[calc(100dvh-2rem)] min-w-0 w-[calc(100vw-2rem)] flex-col overflow-hidden p-0 sm:w-[32rem]"
							size="lg"
						>
							<form onSubmit={handleCreate} className="flex min-h-0 flex-1 flex-col">
								<div className="flex shrink-0 items-start justify-between gap-4 border-b border-kumo-line px-6 py-5">
									<div className="min-w-0">
										<Dialog.Title className="text-lg font-semibold leading-6">
											{t`Create menu`}
										</Dialog.Title>
										<Dialog.Description className="mt-1 text-sm leading-5 text-kumo-subtle">
											{t`Give this navigation a label and a site identifier.`}
										</Dialog.Description>
									</div>
									<Dialog.Close
										render={(props) => (
											<Button
												{...props}
												type="button"
												variant="ghost"
												shape="square"
												icon={<X className="size-4" aria-hidden="true" />}
												aria-label={t`Close`}
											/>
										)}
									/>
								</div>
								<div className="min-h-0 flex-1 space-y-4 overflow-y-auto px-6 py-5">
									<div>
										<Input
											label={t`Label`}
											name="label"
											required
											placeholder={t`Primary navigation`}
										/>
										<p className="mt-1 text-sm text-kumo-subtle">{t`Shown in the admin menu list.`}</p>
									</div>
									<div>
										<Input
											label={t`Name`}
											name="name"
											dir="ltr"
											required
											placeholder={t`primary`}
											pattern="[a-z0-9\-]+"
											title={t`Only lowercase letters, numbers, and hyphens`}
										/>
										<p className="mt-1 text-sm text-kumo-subtle">
											{t`Stable identifier for your site, such as primary or footer.`}
										</p>
									</div>
									<DialogError message={getMutationError(createMutation.error)} />
								</div>
								<div className="flex shrink-0 justify-end gap-2 border-t border-kumo-line px-6 py-4">
									<Button
										type="button"
										variant="secondary"
										onClick={() => handleCreateOpenChange(false)}
									>
										{t`Cancel`}
									</Button>
									<Button type="submit" variant="primary" disabled={createMutation.isPending}>
										{createMutation.isPending ? t`Creating...` : t`Create`}
									</Button>
								</div>
							</form>
						</Dialog>
					</Dialog.Root>
				</div>
			</header>

			{!menus || menus.length === 0 ? (
				<LayerCard className="flex flex-col items-center px-6 py-16 text-center">
					<span className="mb-5 flex size-14 items-center justify-center rounded-xl bg-kumo-tint text-kumo-brand">
						<ADMIN_NAV_ICONS.menus size={28} aria-hidden="true" />
					</span>
					<h2 className="text-lg font-semibold leading-6">{t`No menus yet`}</h2>
					<p className="mt-2 max-w-sm text-sm leading-5 text-pretty text-kumo-subtle">
						{t`Create your first navigation menu to get started`}
					</p>
					<Button
						className="mt-5"
						icon={<Plus aria-hidden="true" />}
						onClick={() => handleCreateOpenChange(true)}
					>
						{t`Create Menu`}
					</Button>
				</LayerCard>
			) : (
				<ul className="grid gap-4 lg:grid-cols-2">
					{menus.map((menu) => (
						<li key={menu.id}>
							<MenuCard
								menu={menu}
								showLocale={!!i18n}
								onDelete={() => setDeleteMenuName(menu.name)}
							/>
						</li>
					))}
				</ul>
			)}

			<ConfirmDialog
				open={deleteMenuName !== null}
				onClose={() => {
					setDeleteMenuName(null);
					deleteMutation.reset();
				}}
				title={t`Delete menu`}
				description={t`Are you sure you want to delete this menu? This will also delete all menu items. This action cannot be undone.`}
				confirmLabel={t`Delete`}
				pendingLabel={t`Deleting...`}
				isPending={deleteMutation.isPending}
				error={deleteMutation.error}
				onConfirm={() => deleteMenuName && deleteMutation.mutate(deleteMenuName)}
			/>
		</div>
	);
}
