// src/lib/dashboard/Dashboard.svelte
<script lang="ts">
  // Native Svelte transport for pinned Dashboard.tsx; Source fixture assertions
  // remain complete. Copyright 2026 Cloudflare Inc. MIT; notices/emdash-MIT.txt.
  import { onMount, untrack } from 'svelte';
  import { Card, CardHeader, CardContent } from '../ui/vendor/sveltery/card/index';
  import { createDashboardClient } from './client';
  import { formatRelativeTime } from './time';
  import type { DashboardClient, DashboardManifest, DashboardStats } from './types';
  let { manifest, user, client: suppliedClient, basePath = '', locale = 'en' }: {
    manifest: DashboardManifest; user?: { role: number } | null; client?: DashboardClient;
    basePath?: string; locale?: string;
  } = $props();
  const client = $derived(suppliedClient ?? createDashboardClient(basePath));
  let stats = $state<DashboardStats>();
  let loading = $state(true);
  let error = $state(false);
  let policyError = $state<string | null>(null);
  let dismissPending = $state(false);
  let importDismissed = $state(false);
  let importable = $state(false);
  let importRequest: Promise<void> | undefined;
  let active = true;
  const role = $derived(user?.role ?? 0);
  const drafts = $derived(stats?.collections.reduce((sum, collection) => sum + collection.draft, 0) ?? 0);
  const scheduled = $derived(stats?.collections.reduce((sum, collection) => sum + collection.scheduled, 0) ?? 0);
  const overdue = $derived(stats?.collections.reduce((sum, collection) => sum + (collection.overdueScheduled ?? 0), 0) ?? 0);
  const policyRejected = $derived(stats?.policyRejectedScheduled ?? 0);
  const rejections = $derived(stats?.policyRejections ?? []);
  const schedulerNeedsAttention = $derived(overdue > 0 && stats?.schedulerHealth !== undefined && stats.schedulerHealth.status !== 'healthy');
  const quickActions = $derived(Object.entries(manifest.collections).filter(([, collection]) => !collection.hidden && collection.quickCreate !== false));
  const statusLabels: Record<string, string> = { published: 'Published', draft: 'Draft', scheduled: 'Scheduled', pending: 'Pending changes', pending_changes: 'Pending changes', private: 'Private', archived: 'Archived' };
  const hintKey = 'emdash:dashboard:site-import-hint-dismissed';
  const href = (path: string) => `${basePath}${path}`;
  const importEnabled = $derived(role >= 50 && !importDismissed && stats !== undefined && stats.mediaCount === 0 && stats.collections.every(collection => collection.total === 0));
  function checkImport(requestClient: DashboardClient = client): Promise<void> {
    if (!active || !importEnabled) return Promise.resolve();
    if (importRequest) return importRequest;
    importRequest = Promise.resolve().then(async () => {
      try { const capabilities = await requestClient.fetchTransferCapabilities(); if (active && importEnabled) importable = capabilities.portableDomain.empty; }
      catch { /* Source retains cached eligibility on a later error; no initial data means no suggestion. */ }
      finally { importRequest = undefined; }
    });
    return importRequest;
  }
  $effect(() => {
    const enabled = importEnabled;
    const requestClient = client;
    if (enabled) untrack(() => { void checkImport(requestClient); });
    else importable = false;
  });
  async function refresh() {
    try { const value = await client.fetchDashboardStats(); if (active) { stats = value; error = false; } }
    catch { if (active) error = true; }
    finally { if (active) loading = false; }
  }
  async function dismissPolicy(collection: string, id: string, revision: string) {
    dismissPending = true; policyError = null;
    try { await client.dismissScheduledPolicyRejection(collection, id, revision); }
    catch (cause) { if (active) policyError = cause instanceof Error ? cause.message : 'An error occurred'; }
    finally { await refresh(); if (active) dismissPending = false; }
  }
  function dismissImport() {
    importDismissed = true;
    try { localStorage.setItem(hintKey, '1'); } catch { /* Optional preference only. */ }
  }
  onMount(() => {
    active = true;
    try { importDismissed = localStorage.getItem(hintKey) === '1'; } catch { /* Denied storage retains the Source default. */ }
    void refresh();
    const focus = () => { void refresh(); void checkImport(); };
    window.addEventListener('focus', focus);
    return () => { active = false; window.removeEventListener('focus', focus); };
  });
</script>

<div class="dashboard">
  {#if manifest.marketplace && role >= 50}
    <section class="notice" role="status"><h2>Marketplace configuration is deprecated</h2><p>New plugin discovery uses the registry. Existing marketplace plugins can still be updated or uninstalled while you switch over.</p><a href="https://docs.emdashcms.com/plugins/migrate-from-marketplace/">Migration guide</a></section>
  {/if}
  <header class="dashboard-header"><h1>Dashboard</h1><div class="quick-actions">
    {#each quickActions as [slug, collection] (slug)}<a class="button" href={href(`/content/${encodeURIComponent(slug)}/new`)}>{collection.labelSingular ?? collection.label}</a>{/each}
    <a class="button" href={href('/media')}>Upload Media</a>
  </div></header>
  {#if error}<section class="notice" role="alert"><strong>Could not load dashboard data</strong><p>Refresh the page or try again.</p></section>{/if}
  {#if !error || stats}
    {#if stats && role >= 50 && importable && !importDismissed && stats.mediaCount === 0 && stats.collections.every(collection => collection.total === 0)}
      <section class="notice"><h2>Moving from another EmDash site?</h2><p>This site has no content yet, so you can import a .emdash package exported from another EmDash site.</p><a class="button" href={href('/settings/transfer?start=import')}>Import a site package</a><button type="button" aria-label="Dismiss import suggestion" onclick={dismissImport}>×</button></section>
    {/if}
    {#if stats && policyRejected > 0}
      <section class="notice" role="alert">
        <h2>Publication policy blocked scheduled content</h2>
        <p>{policyRejected === 1 ? 'Open the affected entry, resolve the policy reason, and schedule it again. A successful schedule or publish clears this notice.' : 'Open the affected entries, resolve the policy reasons, and schedule them again. A successful schedule or publish clears each notice.'}</p>
        {#if rejections.length}<ul>{#each rejections as rejection (`${rejection.collection}:${rejection.id}`)}<li><a href={href(`/content/${encodeURIComponent(rejection.collection)}/${encodeURIComponent(rejection.id)}`)}><bdi dir="ltr">{rejection.collection}/{rejection.id}</bdi></a><p>{rejection.reason}</p>{#if role >= 40}<button type="button" disabled={dismissPending} onclick={() => void dismissPolicy(rejection.collection, rejection.id, rejection._rev)}>Dismiss</button>{/if}</li>{/each}</ul>{/if}
        {#if policyRejected > rejections.length}<p>{policyRejected - rejections.length === 1 ? 'One more blocked entry is not shown.' : `${policyRejected - rejections.length} more blocked entries are not shown.`}</p>{/if}
        {#if policyError}<p role="alert">{policyError}</p>{/if}
      </section>
    {/if}
    {#if schedulerNeedsAttention}
      <section class="notice" role="alert"><h2>Scheduled publishing needs attention</h2><p>{overdue === 1 ? 'One scheduled item is overdue' : `${overdue} scheduled items are overdue`}{stats?.schedulerHealth?.status === 'unknown' ? ', but no scheduler run has completed.' : ' and the scheduler heartbeat is stale.'} Check the scheduled publishing configuration.</p></section>
    {/if}
    {#if loading}<div class="metrics" aria-label="Loading dashboard data" aria-busy="true">{#each [1, 2, 3] as key (key)}<Card class="skeleton"><CardContent><span class="skeleton-line"></span><span class="skeleton-line short"></span></CardContent></Card>{/each}</div>
    {:else if stats}
      <div class="metrics">
        <Card><CardHeader><h2>{drafts === 1 ? 'Draft' : 'Drafts'}</h2></CardHeader><CardContent><span data-testid="dashboard-metric-value">{drafts}</span></CardContent></Card>
        {#if scheduled > 0}<Card><CardHeader><h2>{#if role >= 20}<a href={href('/calendar')}>Scheduled</a>{:else}Scheduled{/if}</h2></CardHeader><CardContent><span data-testid="dashboard-metric-value">{scheduled}</span></CardContent></Card>{/if}
        <Card><CardHeader><h2>{stats.mediaCount === 1 ? 'Media file' : 'Media files'}</h2></CardHeader><CardContent><span data-testid="dashboard-metric-value">{stats.mediaCount}</span></CardContent></Card>
        <Card><CardHeader><h2>{stats.userCount === 1 ? 'User' : 'Users'}</h2></CardHeader><CardContent><span data-testid="dashboard-metric-value">{stats.userCount}</span></CardContent></Card>
      </div>
    {/if}
    <div class="details">
      <Card><CardHeader><h2>Content</h2></CardHeader><CardContent>
        {#if loading}<p aria-busy="true">Loading content…</p>{:else if !stats?.collections.length}<p class="muted">No collections configured</p>
        {:else}<ul>{#each stats.collections as collection (collection.slug)}<li><a class="row" href={href(`/content/${encodeURIComponent(collection.slug)}`)}><span>{manifest.collections[collection.slug]?.label ?? collection.label}</span><span class="counts">{#if collection.published > 0}<span class="badge"><span class="sr-only">Published</span>{collection.published}</span>{/if}{#if collection.draft > 0}<span class="badge"><span class="sr-only">Drafts</span>{collection.draft}</span>{/if}</span></a></li>{/each}</ul>{/if}
      </CardContent></Card>
      <Card><CardHeader><h2>Recent Activity</h2></CardHeader><CardContent>
        {#if loading}<p aria-busy="true">Loading recent activity…</p>{:else if !stats?.recentItems.length}<p class="muted">No recent activity</p>
        {:else}<ul>{#each stats.recentItems as item (`${item.collection}-${item.id}`)}<li><a class="row" href={href(`/content/${encodeURIComponent(item.collection)}/${encodeURIComponent(item.id)}`)}><span class="activity-title"><span class="status-dot" role="img" aria-label={Object.hasOwn(statusLabels, item.status) ? statusLabels[item.status] : `Status: ${item.status}`}></span><span>{item.title || item.slug || 'Untitled'}</span><small class="collection-label muted">{item.collectionLabel}</small></span><time data-testid="activity-time" datetime={item.updatedAt}>{formatRelativeTime(item.updatedAt, locale)}</time></a></li>{/each}</ul>{/if}
      </CardContent></Card>
    </div>
  {/if}
</div>

<style>
  .dashboard { display: grid; gap: 24px; }
  .dashboard-header { display: flex; align-items: center; justify-content: space-between; gap: 16px; flex-wrap: wrap; }
  h1 { font-size: 28px; margin: 0; letter-spacing: -.02em; }
  h2 { font-size: 15px; line-height: 1.4; margin: 0; font-weight: 600; }
  p { font-size: 14px; line-height: 1.6; text-wrap: pretty; }
  .quick-actions, .counts { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }
  .metrics { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); }
  .details { display: grid; gap: 24px; grid-template-columns: repeat(2, minmax(0, 1fr)); }
  :global(.dashboard [data-slot=card]) { border: 1px solid var(--border, #d6d6d6); border-radius: 9px; background: var(--card, white); color: var(--card-foreground, #171717); }
  :global(.dashboard [data-slot=card-header]) { padding: 14px 16px; background: var(--muted, #f4f4f4); border-bottom: 1px solid var(--border, #d6d6d6); border-radius: 9px 9px 0 0; }
  :global(.dashboard [data-slot=card-content]) { padding: 16px; }
  [data-testid=dashboard-metric-value] { font-size: 30px; font-weight: 650; font-variant-numeric: tabular-nums; }
  .notice { background: var(--muted, #f4f4f4); border: 1px solid var(--border, #d6d6d6); border-radius: 9px; padding: 16px; }
  .notice h2 { font-size: 16px; }
  ul { padding: 0; margin: 0; list-style: none; }
  li + li { margin-top: 8px; }
  .row { display: flex; align-items: center; justify-content: space-between; gap: 12px; border-radius: 6px; padding: 10px 0; text-decoration: none; }
  .row:hover { background: var(--muted, #f4f4f4); }
  .activity-title { display: flex; align-items: center; gap: 8px; min-width: 0; }
  .activity-title > span:not(.status-dot) { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .status-dot { flex: 0 0 10px; width: 10px; height: 10px; border-radius: 50%; background: var(--muted-foreground, #606060); }
  .badge { background: var(--muted, #f4f4f4); border: 1px solid var(--border, #d6d6d6); border-radius: 999px; padding: 2px 8px; font-size: 12px; font-variant-numeric: tabular-nums; }
  time { font-size: 12px; white-space: nowrap; color: var(--muted-foreground, #606060); }
  .button, button { display: inline-flex; border: 1px solid var(--border, #d6d6d6); border-radius: 6px; background: var(--background, white); padding: 8px 12px; font: inherit; font-size: 13px; color: inherit; text-decoration: none; cursor: pointer; }
  button:disabled { opacity: .65; cursor: wait; }
  a:focus-visible, button:focus-visible { outline: 2px solid var(--ring, #707070); outline-offset: 3px; }
  .muted { color: var(--muted-foreground, #606060); }
  .sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0; }
  .skeleton-line { display: block; width: 70%; height: 15px; border-radius: 5px; background: var(--muted, #ededed); margin: 12px 0; }
  .short { width: 30%; height: 30px; }
  @media (max-width: 760px) { .details { grid-template-columns: 1fr; } .collection-label { display: none; } }
</style>

// parity/emdash/dashboard-welcome-source/upstream/packages/admin/src/components/Dashboard.tsx
import { Badge, Banner, Button, LayerCard, SkeletonLine } from "@cloudflare/kumo";
import { plural } from "@lingui/core/macro";
import { useLingui } from "@lingui/react/macro";
import { FileArrowUp, Plus, Upload, X } from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import * as React from "react";

import type { AdminManifest } from "../lib/api";
import { useCurrentUser } from "../lib/api/current-user.js";
import type { CollectionStats, DashboardStats, RecentItem } from "../lib/api/dashboard";
import { dismissScheduledPolicyRejection, fetchDashboardStats } from "../lib/api/dashboard";
import { fetchTransferCapabilities, TRANSFER_CAPABILITIES_QUERY_KEY } from "../lib/api/transfer.js";
import { usePluginWidget } from "../lib/plugin-context";
import { cn, formatRelativeTime } from "../lib/utils";
import { ArrowNext } from "./ArrowIcons";
import {
	ContentStatusIcon,
	CONTENT_STATUS_ICONS,
	type ContentStatusState,
} from "./ContentStatusBadge.js";
import { CoreUpdateBanner } from "./CoreUpdateBanner.js";
import { getMutationError } from "./DialogError.js";
import { MarketplaceMigrationBanner } from "./MarketplaceMigrationBanner.js";
import { RouterLinkButton } from "./RouterLinkButton";
import { SandboxedPluginWidget } from "./SandboxedPluginWidget";
import { visibleCollectionEntries } from "./Sidebar.js";

const DASHBOARD_STATUS_STATES: Record<string, ContentStatusState> = {
	published: "published",
	draft: "draft",
	scheduled: "scheduled",
	pending: "pendingChanges",
	pending_changes: "pendingChanges",
	private: "private",
	archived: "archived",
};

const ROLE_ADMIN = 50;
const ROLE_EDITOR = 40;
const ROLE_CONTRIBUTOR = 20;

const SITE_IMPORT_HINT_DISMISSED_KEY = "emdash:dashboard:site-import-hint-dismissed";

export interface DashboardProps {
	manifest: AdminManifest;
}

/**
 * Admin dashboard — quick actions, status, collections, recent activity.
 */
export function Dashboard({ manifest }: DashboardProps) {
	const { t } = useLingui();
	const { data: user } = useCurrentUser();
	const {
		data: stats,
		isLoading,
		isError,
	} = useQuery({
		queryKey: ["dashboard-stats"],
		queryFn: fetchDashboardStats,
		refetchOnWindowFocus: true,
	});
	const hasDashboardData = stats !== undefined;
	const showDashboardData = !isError || hasDashboardData;

	return (
		<div className="space-y-6">
			{manifest.marketplace && (user?.role ?? 0) >= ROLE_ADMIN && <MarketplaceMigrationBanner />}
			<div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
				<h1 className="text-2xl font-semibold leading-tight">{t`Dashboard`}</h1>
				<QuickActions manifest={manifest} />
			</div>

			<CoreUpdateBanner />

			{isError && <DashboardDataError />}

			{showDashboardData && (
				<>
					{stats && (user?.role ?? 0) >= ROLE_ADMIN && <SiteImportHint stats={stats} />}
					{stats && (
						<SchedulerWarning stats={stats} canDismissPolicy={(user?.role ?? 0) >= ROLE_EDITOR} />
					)}
					<SummaryMetrics
						stats={stats}
						loading={isLoading}
						linkCalendar={(user?.role ?? 0) >= ROLE_CONTRIBUTOR}
					/>

					{/* Collections + Recent activity */}
					<div className="grid gap-6 lg:grid-cols-2">
						<CollectionList
							collections={stats?.collections ?? []}
							manifest={manifest}
							loading={isLoading}
						/>
						<RecentActivity items={stats?.recentItems ?? []} loading={isLoading} />
					</div>
				</>
			)}

			{/* Plugin widgets */}
			<PluginWidgets manifest={manifest} />
		</div>
	);
}

function SchedulerWarning({
	stats,
	canDismissPolicy,
}: {
	stats: DashboardStats;
	canDismissPolicy: boolean;
}) {
	const { t } = useLingui();
	const queryClient = useQueryClient();
	const dismissMutation = useMutation({
		mutationFn: ({
			collection,
			id,
			revision,
		}: {
			collection: string;
			id: string;
			revision: string;
		}) => dismissScheduledPolicyRejection(collection, id, revision),
		onSettled: async () => {
			await queryClient.invalidateQueries({ queryKey: ["dashboard-stats"] });
		},
	});
	const policyRejected = stats.policyRejectedScheduled ?? 0;
	const policyRejections = stats.policyRejections ?? [];
	const overdueCount = stats.collections.reduce(
		(sum, collection) => sum + (collection.overdueScheduled ?? 0),
		0,
	);
	const schedulerNeedsAttention =
		overdueCount > 0 &&
		stats.schedulerHealth !== undefined &&
		stats.schedulerHealth.status !== "healthy";
	if (policyRejected === 0 && !schedulerNeedsAttention) return null;

	const schedulerDescription = schedulerNeedsAttention
		? stats.schedulerHealth!.status === "unknown"
			? plural(overdueCount, {
					one: "One scheduled item is overdue, but no scheduler run has completed. Run `npx emdash doctor` and verify the deployed Cron Trigger.",
					other:
						"# scheduled items are overdue, but no scheduler run has completed. Run `npx emdash doctor` and verify the deployed Cron Trigger.",
				})
			: plural(overdueCount, {
					one: "One scheduled item is overdue and the scheduler heartbeat is stale. Run `npx emdash doctor` and verify the deployed Cron Trigger.",
					other:
						"# scheduled items are overdue and the scheduler heartbeat is stale. Run `npx emdash doctor` and verify the deployed Cron Trigger.",
				})
		: "";

	return (
		<div className="space-y-3">
			{policyRejected > 0 && (
				<div className="space-y-2">
					<Banner
						variant="alert"
						title={t`Publication policy blocked scheduled content`}
						description={plural(policyRejected, {
							one: "Open the affected entry, resolve the policy reason, and schedule it again. A successful schedule or publish clears this notice.",
							other:
								"Open the affected entries, resolve the policy reasons, and schedule them again. A successful schedule or publish clears each notice.",
						})}
						role="alert"
					/>
					{policyRejections.length > 0 && (
						<ul className="space-y-2">
							{policyRejections.map((rejection) => (
								<li key={`${rejection.collection}:${rejection.id}`}>
									<LayerCard.Secondary className="p-3">
										<Link
											to="/content/$collection/$id"
											params={{ collection: rejection.collection, id: rejection.id }}
											className="font-medium text-kumo-brand hover:underline"
										>
											<bdi dir="ltr">
												{rejection.collection}/{rejection.id}
											</bdi>
										</Link>
										<p className="mt-1 text-sm text-kumo-subtle">{rejection.reason}</p>
										{canDismissPolicy && (
											<Button
												variant="secondary"
												size="sm"
												className="mt-2"
												disabled={dismissMutation.isPending}
												onClick={() =>
													dismissMutation.mutate({
														collection: rejection.collection,
														id: rejection.id,
														revision: rejection._rev,
													})
												}
											>
												{t`Dismiss`}
											</Button>
										)}
									</LayerCard.Secondary>
								</li>
							))}
						</ul>
					)}
					{policyRejected > policyRejections.length && (
						<p className="text-sm text-kumo-subtle">
							{plural(policyRejected - policyRejections.length, {
								one: "One more blocked entry is not shown.",
								other: "# more blocked entries are not shown.",
							})}
						</p>
					)}
					{dismissMutation.isError && (
						<p className="text-sm text-kumo-danger" role="alert">
							{getMutationError(dismissMutation.error) ??
								t`Failed to dismiss scheduled publication rejection`}
						</p>
					)}
				</div>
			)}
			{schedulerNeedsAttention && (
				<Banner
					variant="alert"
					title={t`Scheduled publishing needs attention`}
					description={schedulerDescription}
					role="alert"
				/>
			)}
		</div>
	);
}

function readSiteImportHintDismissed(): boolean {
	try {
		return window.localStorage.getItem(SITE_IMPORT_HINT_DISMISSED_KEY) === "1";
	} catch {
		return false;
	}
}

function SiteImportHint({ stats }: { stats: DashboardStats }) {
	const { t } = useLingui();
	const [dismissed, setDismissed] = React.useState(readSiteImportHintDismissed);
	// Any content or media rules out an import, so only ask the server when the
	// counts already loaded for the dashboard leave it possible.
	const mayBeEmpty =
		stats.mediaCount === 0 && stats.collections.every((collection) => collection.total === 0);
	const { data: capabilities } = useQuery({
		queryKey: TRANSFER_CAPABILITIES_QUERY_KEY,
		queryFn: fetchTransferCapabilities,
		enabled: !dismissed && mayBeEmpty,
	});

	if (dismissed || !mayBeEmpty || !capabilities?.portableDomain.empty) return null;

	const dismiss = () => {
		setDismissed(true);
		try {
			window.localStorage.setItem(SITE_IMPORT_HINT_DISMISSED_KEY, "1");
		} catch {
			// Without storage the hint stays hidden until the next page load.
		}
	};

	return (
		<Banner
			variant="secondary"
			icon={<FileArrowUp aria-hidden="true" />}
			title={t`Moving from another EmDash site?`}
			description={t`This site has no content yet, so you can import a .emdash package exported from another EmDash site.`}
			action={
				<div className="flex items-center gap-1">
					<RouterLinkButton
						to="/settings/transfer"
						search={{ start: "import" }}
						variant="secondary"
						size="sm"
					>
						{t`Import a site package`}
					</RouterLinkButton>
					<Button
						type="button"
						variant="ghost"
						size="sm"
						shape="square"
						onClick={dismiss}
						aria-label={t`Dismiss import suggestion`}
					>
						<X className="h-4 w-4" aria-hidden="true" />
					</Button>
				</div>
			}
		/>
	);
}

function DashboardDataError() {
	const { t } = useLingui();

	return (
		<Banner
			variant="error"
			title={t`Could not load dashboard data`}
			description={t`Refresh the page or try again.`}
		/>
	);
}

function DashboardCardHeading({ children }: { children: React.ReactNode }) {
	return (
		<LayerCard.Secondary>
			<h2 className="px-3">{children}</h2>
		</LayerCard.Secondary>
	);
}

function DashboardCardInset({ className, ...props }: React.ComponentPropsWithoutRef<"div">) {
	return <div className={cn("px-3", className)} {...props} />;
}

// --- Quick actions ---

function QuickActions({ manifest }: { manifest: AdminManifest }) {
	const { t } = useLingui();
	const collections = visibleCollectionEntries(manifest.collections).filter(
		([, config]) => config.quickCreate !== false,
	);

	return (
		<div className="flex flex-wrap items-center gap-2">
			{collections.map(([slug, config]) => (
				<RouterLinkButton
					key={slug}
					to="/content/$collection/new"
					params={{ collection: slug }}
					search={{ locale: undefined }}
					variant="secondary"
					icon={<Plus aria-hidden="true" />}
				>
					{config.labelSingular ?? config.label}
				</RouterLinkButton>
			))}
			<RouterLinkButton to="/media" variant="secondary" icon={<Upload aria-hidden="true" />}>
				{t`Upload Media`}
			</RouterLinkButton>
		</div>
	);
}

// --- Summary metrics ---

function SummaryMetrics({
	stats,
	loading,
	linkCalendar,
}: {
	stats?: DashboardStats;
	loading: boolean;
	/** Link the Scheduled count to the calendar, for roles that can open it. */
	linkCalendar: boolean;
}) {
	if (loading) {
		return (
			<div className="grid gap-4 sm:grid-cols-3">
				{[1, 2, 3].map((i) => (
					<LayerCard key={i}>
						<LayerCard.Secondary>
							<DashboardCardInset>
								<SkeletonLine minWidth={45} maxWidth={70} />
							</DashboardCardInset>
						</LayerCard.Secondary>
						<LayerCard.Primary className="text-3xl font-semibold leading-none">
							<DashboardCardInset>
								<SkeletonLine minWidth={20} maxWidth={35} />
							</DashboardCardInset>
						</LayerCard.Primary>
					</LayerCard>
				))}
			</div>
		);
	}

	if (!stats) return null;

	const totalDrafts = stats.collections.reduce((sum, c) => sum + c.draft, 0);
	const totalScheduled = stats.collections.reduce((sum, c) => sum + c.scheduled, 0);
	const hasScheduledContent = totalScheduled > 0;

	const metrics: Array<{ label: string; value: number; calendar?: boolean }> = [
		{
			label: plural(totalDrafts, { one: "Draft", other: "Drafts" }),
			value: totalDrafts,
		},
		...(hasScheduledContent
			? [
					{
						label: plural(totalScheduled, { one: "Scheduled", other: "Scheduled" }),
						value: totalScheduled,
						calendar: linkCalendar,
					},
				]
			: []),
		{
			label: plural(stats.mediaCount, { one: "Media file", other: "Media files" }),
			value: stats.mediaCount,
		},
		{
			label: plural(stats.userCount, { one: "User", other: "Users" }),
			value: stats.userCount,
		},
	];

	return (
		<div
			className={
				hasScheduledContent
					? "grid gap-4 sm:grid-cols-2 lg:grid-cols-4"
					: "grid gap-4 sm:grid-cols-3"
			}
		>
			{metrics.map((metric) => (
				<LayerCard key={metric.label} data-testid="dashboard-metric">
					<DashboardCardHeading>
						{metric.calendar ? (
							<Link
								to="/calendar"
								className="group inline-flex items-center gap-1 rounded-sm hover:text-kumo-default focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-kumo-brand"
							>
								{metric.label}
								<ArrowNext
									aria-hidden="true"
									className="size-3.5 opacity-60 transition-opacity group-hover:opacity-100 motion-reduce:transition-none"
								/>
							</Link>
						) : (
							metric.label
						)}
					</DashboardCardHeading>
					<LayerCard.Primary className="text-3xl font-semibold leading-none tabular-nums">
						<DashboardCardInset data-testid="dashboard-metric-value">
							{metric.value}
						</DashboardCardInset>
					</LayerCard.Primary>
				</LayerCard>
			))}
		</div>
	);
}

function SkeletonRows({ count }: { count: number }) {
	return (
		<DashboardCardInset className="space-y-3">
			{Array.from({ length: count }, (_, i) => (
				<SkeletonLine key={i} blockHeight={40} minWidth={65} maxWidth={95} />
			))}
		</DashboardCardInset>
	);
}

// --- Collection list with counts ---

function CollectionList({
	collections,
	manifest,
	loading,
}: {
	collections: CollectionStats[];
	manifest: AdminManifest;
	loading: boolean;
}) {
	const { t } = useLingui();

	return (
		<LayerCard className="h-full">
			<DashboardCardHeading>{t`Content`}</DashboardCardHeading>
			<LayerCard.Primary className="flex-1">
				{loading ? (
					<SkeletonRows count={3} />
				) : collections.length === 0 ? (
					<p className="px-3 text-sm leading-6 text-pretty text-kumo-subtle">
						{t`No collections configured`}
					</p>
				) : (
					<div className="space-y-1">
						{collections.map((col) => {
							const config = manifest.collections[col.slug];
							return (
								<Link
									key={col.slug}
									to="/content/$collection"
									params={{ collection: col.slug }}
									search={{ locale: undefined }}
									className="group flex items-center justify-between gap-2 rounded-md px-3 py-2 hover:bg-kumo-tint"
								>
									<span className="text-base font-medium leading-5">
										{config?.label ?? col.label}
									</span>
									<span className="flex shrink-0 items-center gap-2">
										<CountBadge
											icon={CONTENT_STATUS_ICONS.published}
											count={col.published}
											variant="success"
											label={t`Published`}
										/>
										<CountBadge
											icon={CONTENT_STATUS_ICONS.draft}
											count={col.draft}
											variant="warning"
											label={t`Drafts`}
										/>
										<ArrowNext
											className="h-3.5 w-3.5 text-kumo-subtle opacity-0 transition-opacity group-hover:opacity-100"
											aria-hidden="true"
										/>
									</span>
								</Link>
							);
						})}
					</div>
				)}
			</LayerCard.Primary>
		</LayerCard>
	);
}

function CountBadge({
	icon: Icon,
	count,
	variant,
	label,
}: {
	icon: React.ElementType;
	count: number;
	variant: "success" | "warning";
	label: string;
}) {
	if (count === 0) return null;
	return (
		<Badge variant={variant} className="gap-1 tabular-nums">
			<Icon className="h-3 w-3" aria-hidden="true" />
			<span className="sr-only">{label}</span>
			{count}
		</Badge>
	);
}

// --- Recent activity ---

function RecentActivity({ items, loading }: { items: RecentItem[]; loading: boolean }) {
	const { t, i18n } = useLingui();

	return (
		<LayerCard className="h-full">
			<DashboardCardHeading>{t`Recent Activity`}</DashboardCardHeading>
			<LayerCard.Primary className="flex-1">
				{loading ? (
					<SkeletonRows count={5} />
				) : items.length === 0 ? (
					<p className="px-3 text-sm leading-6 text-pretty text-kumo-subtle">
						{t`No recent activity`}
					</p>
				) : (
					<div className="space-y-1">
						{items.map((item) => (
							<Link
								key={`${item.collection}-${item.id}`}
								to="/content/$collection/$id"
								params={{ collection: item.collection, id: item.id }}
								className="group flex items-center justify-between gap-2 rounded-md px-3 py-2 hover:bg-kumo-tint"
							>
								<div className="flex min-w-0 items-center gap-2">
									<StatusDot status={item.status} />
									<span className="truncate text-base font-medium leading-5">
										{item.title || item.slug || t`Untitled`}
									</span>
									<span className="hidden shrink-0 text-xs font-normal leading-5 text-kumo-subtle sm:inline">
										{item.collectionLabel}
									</span>
								</div>
								<span
									data-testid="activity-time"
									className="shrink-0 text-xs font-normal leading-5 text-kumo-subtle tabular-nums"
								>
									{formatRelativeTime(item.updatedAt, i18n.locale)}
								</span>
							</Link>
						))}
					</div>
				)}
			</LayerCard.Primary>
		</LayerCard>
	);
}

function StatusDot({ status }: { status: string }) {
	const { t } = useLingui();
	const state = Object.hasOwn(DASHBOARD_STATUS_STATES, status)
		? DASHBOARD_STATUS_STATES[status]
		: undefined;

	return state ? (
		<ContentStatusIcon state={state} className="shrink-0" />
	) : (
		<span
			className="h-3.5 w-3.5 shrink-0 rounded-full bg-kumo-fill"
			role="img"
			aria-label={t`Status: ${status}`}
		/>
	);
}

// --- Plugin widgets ---

function PluginWidgets({ manifest }: { manifest: AdminManifest }) {
	const widgets: Array<{
		id: string;
		pluginId: string;
		title?: string;
		size?: "full" | "half" | "third";
	}> = [];

	for (const [pluginId, plugin] of Object.entries(manifest.plugins || {})) {
		if (plugin.enabled === false) continue;

		if ("dashboardWidgets" in plugin && Array.isArray(plugin.dashboardWidgets)) {
			for (const widget of plugin.dashboardWidgets) {
				widgets.push({
					id: widget.id,
					pluginId,
					title: widget.title,
					size: widget.size,
				});
			}
		}
	}

	if (widgets.length === 0) {
		return null;
	}

	return (
		<div className="grid gap-6 lg:grid-cols-2">
			{widgets.map((widget) => (
				<PluginWidgetCard key={`${widget.pluginId}:${widget.id}`} widget={widget} />
			))}
		</div>
	);
}

function PluginWidgetCard({
	widget,
}: {
	widget: { id: string; pluginId: string; title?: string; size?: string };
}) {
	const WidgetComponent = usePluginWidget(widget.pluginId, widget.id);

	return (
		<LayerCard className="h-full">
			<DashboardCardHeading>{widget.title || widget.id}</DashboardCardHeading>
			<LayerCard.Primary className="flex-1">
				<DashboardCardInset>
					{WidgetComponent ? (
						<WidgetComponent />
					) : (
						<SandboxedPluginWidget pluginId={widget.pluginId} widgetId={widget.id} />
					)}
				</DashboardCardInset>
			</LayerCard.Primary>
		</LayerCard>
	);
}
