// src/lib/calendar/CalendarEntryPanel.svelte
<script lang="ts">
  import { useCalendarMessages } from './message-context.svelte.ts';
  const t = useCalendarMessages();
  // EmDash1.1.0 CalendarEntryPanel behavior, pin913cb1bb; MIT.
  import { untrack } from 'svelte';
  import {runCalendarPanelAction,runCalendarReschedule} from './panel-actions.ts';
  import {calendarEditedState} from './presentation.ts';
  import ScheduleDialog from './CalendarScheduleDialog.svelte';
  import { contentUrl } from './url.ts';
  import { base } from '$app/paths';
  import { QueryObserver, type QueryClient } from '@tanstack/react-query';
  import { formatTimeAgo,formatTimeUntil,type CalendarDisplay,type CalendarItem } from './calendar.ts';
  import { stateLabels } from './entry.ts';
  import { getLocaleLabel } from '../ui/locales/config.ts';
  import { type CalendarInlineError } from './mutation-error.ts';
  import type { CalendarClient,CalendarContent,CalendarManifest,CalendarUser,CalendarNotice } from './ui-types.ts';
  let { item,display,now,compact, i18n,urlPatterns={},user,onClose,onRescheduled,onNotice,returnFocus,client,queryClient }: {
    item:CalendarItem|undefined;display:CalendarDisplay;now:number;compact:boolean;
    i18n?:CalendarManifest['i18n'];urlPatterns?:Readonly<Record<string,string|undefined>>;user?:CalendarUser;
    onClose:()=>void;onRescheduled:(item:CalendarItem,scheduledAt:string)=>void;onNotice?:(notice:CalendarNotice)=>void;returnFocus?:{current:HTMLElement|null};
    client:CalendarClient;queryClient?:QueryClient;
  }=$props();
  let entry=$state<CalendarContent>(),error=$state<CalendarInlineError|null>(),pending=$state(false),reschedulePending=$state(false),detailsPending=$state(false),scheduleOpen=$state(false),previewing=$state(false),translations=$state<{id:string;locale:string;status:string}[]>([]),dialog=$state<HTMLDialogElement>();
  const selectedKey=$derived(item?.key);
  $effect(()=>{selectedKey;scheduleOpen=false;pending=false;reschedulePending=false;previewing=false;});
  $effect(()=>{
    selectedKey;const selected=untrack(()=>item);if(!selected){entry=undefined;return;}
    entry=undefined;error=undefined;detailsPending=true;let active=true;
    const options={queryKey:['content',selected.collection,selected.id,{locale:i18n?selected.locale:undefined}],queryFn:()=>client.fetchContent(selected.collection,selected.id,{locale:i18n?selected.locale:undefined}),staleTime:0};
    if(queryClient){const observer=new QueryObserver(queryClient,options);const unsubscribe=observer.subscribe(result=>{entry=result.data;detailsPending=result.isPending;error=result.isError?{message:"Could not load this entry's details."}:undefined;});return()=>{active=false;unsubscribe();observer.destroy();};}
    void options.queryFn().then(value=>{if(active){entry=value;detailsPending=false;}},()=>{if(active){detailsPending=false;error={message:"Could not load this entry's details."};}});return()=>{active=false;};
  });
  $effect(()=>{
    selectedKey;const selected=untrack(()=>item),fetch=client.fetchTranslations;translations=[];
    if(!selected||!display.showLocale||!fetch)return;
    const options={queryKey:['translations',selected.collection,selected.id],queryFn:()=>fetch(selected.collection,selected.id)};
    if(queryClient){const observer=new QueryObserver(queryClient,options);const unsubscribe=observer.subscribe(result=>{translations=result.data?.translations??[];});return()=>{unsubscribe();observer.destroy();};}
    let active=true;void options.queryFn().then(result=>{if(active)translations=result.translations;},()=>{});return()=>{active=false;};
  });
  $effect(()=>{
    const selected=selectedKey,node=dialog,isCompact=compact;
    if(selected&&node){
      if(node.open&&isCompact!==node.matches(':modal')){
        // Native dialog modality changes require reopening. Preserve a nested
        // schedule's top-layer ordering and fields without action/history callbacks.
        const focused=document.activeElement instanceof HTMLElement?document.activeElement:null;
        const child=node.querySelector<HTMLDialogElement>('dialog[open]');
        child?.close();node.close();isCompact?node.showModal():node.show();child?.showModal();
        if(focused&&node.contains(focused))focused.focus();
      }else if(!node.open){isCompact?node.showModal():node.show();}
    }else if(node?.open){node.close();returnFocus?.current?.isConnected&&returnFocus.current.focus();}
  });
  const canPublish=$derived(Boolean(user&&entry&&(user.role>=40||(user.role>=30&&entry.authorId===user.id))));
  const bylines=$derived(new Intl.ListFormat(display.locale,{type:'conjunction'}).format((entry?.bylines??[]).toSorted((a,b)=>a.sortOrder-b.sortOrder).map(c=>c.byline.displayName)));
  const others=$derived(translations.filter(translation=>translation.locale!==item?.locale));
  const edited=$derived(entry&&!Number.isNaN(Date.parse(entry.updatedAt))?formatTimeAgo(now-Date.parse(entry.updatedAt),display.locale):'—');
  const liveSince=$derived(entry?.publishedAt&&!Number.isNaN(Date.parse(entry.publishedAt))?display.formatDateTime(Date.parse(entry.publishedAt)):undefined);
  const liveUrl=$derived(item?.state==='published'&&entry?.slug?contentUrl(item.collection,entry.slug,urlPatterns[item.collection],{locale:item.locale,i18n,id:item.id,date:entry.publishedAt}):undefined);
  function refresh(selected:CalendarItem){
    void queryClient?.invalidateQueries({queryKey:['calendar']});
    void queryClient?.invalidateQueries({queryKey:['content',selected.collection]});
    void queryClient?.invalidateQueries({queryKey:['dashboard-stats']});
  }
  async function mutate(action:'publish'|'unschedule') {
    if(!item||pending)return;const selected=item;
    await runCalendarPanelAction(action,selected,{client,rev:entry?._rev,current:()=>item?.key===selected.key,pending:value=>pending=value,error:value=>error=value,genericError:()=>t('An error occurred'),refresh:()=>refresh(selected),
      success:()=>onNotice?.(action==='publish'?{title:t('Published'),description:t('{title} is now live.',{title:selected.title})}:{title:t('Schedule removed'),description:selected.status==='published'?t('The scheduled changes to {title} stay as a draft.',{title:selected.title}):t('{title} is a draft again.',{title:selected.title})}),
      failure:description=>onNotice?.({title:action==='publish'?t('Could not publish'):t('Could not remove the schedule'),description,type:'error'}),close:onClose});
  }
  async function reschedule(at:string){
    if(!item)return;const selected=item;
    await runCalendarReschedule(selected,at,{client,pending:value=>{if(item?.key===selected.key)reschedulePending=value;},current:()=>item?.key===selected.key,refresh:()=>refresh(selected),
      success:()=>onNotice?.({title:t('Rescheduled'),description:t('{title} now goes live {when}.',{title:selected.title,when:display.formatDateTime(Date.parse(at))})}),rescheduled:()=>onRescheduled(selected,at)});
  }
  async function openPreview(){
    if(!item||previewing)return;const selected=item;previewing=true;
    try{
      const result=await client.getPreviewUrl?.(selected.collection,selected.id);
      const fallback=contentUrl(selected.collection,entry?.slug||selected.id,urlPatterns[selected.collection],{locale:selected.locale,i18n,id:selected.id,date:entry?.publishedAt});
      window.open(result?.url??fallback,'_blank','noopener,noreferrer');
    }finally{if(item?.key===selected.key)previewing=false;}
  }
</script>
<dialog bind:this={dialog} closedby={compact?'any':'closerequest'} aria-label={item?.title} data-open={item?'':undefined} class:compact oncancel={event=>{event.preventDefault();onClose();}}>
{#if item}<div class="top"><span>{display.collection(item.collection).label}</span><button type="button" aria-label={t("Close")} onclick={onClose}>×</button></div>
<h2 dir="auto">{item.title}</h2><dl><dt>{t("State")}</dt><dd>{t(stateLabels[item.state])}</dd><dt>{item.kind==='scheduled'?item.state==='overdue'?t("Was due"):t("Goes live"):t("Published")}</dt><dd>{display.formatDateTime(item.time)}{#if display.viewerZoneDiffers}<small>{t("Your time: {viewerTime}",{viewerTime:display.formatViewerTime(item.time)})}</small>{/if}</dd>
{#if display.showLocale}<dt>{t("Locale")}</dt><dd>{getLocaleLabel(item.locale)} <small>{item.locale.toUpperCase()}</small>{#if others.length}<span class="translations">{t("Translations:")} {#each others as translation(translation.id)}<span title={getLocaleLabel(translation.locale)}>{translation.locale.toUpperCase()}</span>{/each}</span>{/if}</dd>{/if}
{#if bylines}<dt>{t("Bylines")}</dt><dd>{bylines}</dd>{/if}<dt>{t("Last edited")}</dt><dd>{#if calendarEditedState(detailsPending,Boolean(entry))==='pending'}<span class="details-loading" aria-hidden="true"></span>{:else}{edited}{/if}</dd></dl>
{#if item.kind==='scheduled'}<h3>{t("Publishing")}</h3>
  {#if item.state==='overdue'}<p class="overdue">{t("This entry was due {lateness} but hasn't published. Scheduled publishing may not be running.",{lateness:formatTimeAgo(now-item.time,display.locale)})}</p>
  {:else if item.state==='scheduled'}<ol class="timeline"><li>{t("Draft")}</li><li><strong>{t("Scheduled")}</strong><p>{t("Goes live {countdown}",{countdown:formatTimeUntil(item.time-now,display.locale)})}</p></li></ol>{:else if item.state==='update'}<ol class="timeline"><li><strong>{t("Live version")}</strong>{#if liveSince}<p>{t("Published {liveSince}",{liveSince})}</p>{/if}</li><li><strong>{t("Scheduled changes")}</strong><p>{t("Go live {countdown}",{countdown:formatTimeUntil(item.time-now,display.locale)})}</p></li></ol>{/if}
  {#if canPublish}<div class="actions">{#if item.state==='overdue'}<button type="button" disabled={pending} onclick={()=>void mutate('publish')}>{t("Publish now")}</button>{/if}<button type="button" disabled={pending} onclick={()=>scheduleOpen=true}>{t("Reschedule")}</button><button type="button" disabled={pending} onclick={()=>void mutate('unschedule')}>{t("Remove schedule")}</button></div>{/if}
{/if}
{#if error}<p role="alert">{typeof error==='string'?error:t(error.message)}</p>{/if}
<footer><a href={`${base}/content/${encodeURIComponent(item.collection)}/${encodeURIComponent(item.id)}?locale=${encodeURIComponent(item.locale)}`}>{t("Open in editor")}</a>{#if item.kind==='scheduled'}<button type="button" disabled={previewing} onclick={()=>void openPreview()}>{item.state==='update'?t("Preview changes"):t("Preview")}</button>{/if}{#if liveUrl}<a href={liveUrl} target="_blank" rel="noopener noreferrer">{t("View live")}</a>{/if}</footer>
{#if item.kind==='scheduled'&&canPublish}<ScheduleDialog open={scheduleOpen} entryKey={item.key} scheduledAt={item.at} isLive={item.status==='published'} isPending={reschedulePending} locale={display.locale} onOpenChange={value=>scheduleOpen=value} onSchedule={reschedule}/>{/if}
{/if}</dialog>
<style>.details-loading{display:block;width:5rem;height:1em;border-radius:.25rem;background:var(--muted,#eee);}dialog{box-sizing:border-box;position:fixed;inset-block:0;inset-inline:auto 0;margin:0;border:0;border-left:1px solid var(--border,#ddd);width:27rem;max-width:100vw;height:100dvh;max-height:100dvh;background:var(--card,#fff);color:inherit;padding:1.5rem;box-shadow:-8px 0 24px #0002;z-index:50;}dialog:not([open]){display:none;}.compact{inset:auto 0 0;width:100%;height:auto;max-height:85dvh;border-radius:1rem 1rem 0 0;}dialog::backdrop{background:#0006;}.top{display:flex;justify-content:space-between;align-items:center;}h2{font-size:1.6rem;}dl{display:grid;grid-template-columns:8rem 1fr;gap:.9rem;}dt{color:var(--muted-foreground,#666);}dd{margin:0;}small{display:block;}button{font:inherit;padding:.5rem;border:1px solid var(--border,#ccc);border-radius:.35rem;background:var(--background,#fff);color:inherit;}button{cursor:pointer;}.actions{display:flex;flex-wrap:wrap;gap:.5rem;}.overdue{padding:.75rem;background:#fff0d6;}footer{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center;margin-top:2rem;padding-top:1rem;border-top:1px solid var(--border,#ddd);}[role="alert"]{color:#b32929;}.timeline{padding-left:1.5rem;display:grid;gap:1rem;}.timeline p{margin:.35rem 0 0;}.translations{display:flex;gap:.5rem;flex-wrap:wrap;font-size:.75rem;margin-top:.25rem;}button:focus-visible,a:focus-visible{outline:2px solid var(--ring,#165ccc);outline-offset:2px;}</style>

// parity/emdash/scheduled-publishing-source/upstream/packages/admin/src/components/calendar/CalendarEntryPanel.tsx
import { Button, LinkButton, SkeletonLine, Toast } from "@cloudflare/kumo";
import { Dialog } from "@cloudflare/kumo/primitives";
import { useLingui } from "@lingui/react/macro";
import {
	ArrowsClockwise,
	ArrowSquareOut,
	CalendarDots,
	CheckCircle,
	CircleDashed,
	CircleHalf,
	Clock,
	ClockCounterClockwise,
	Eye,
	PaperPlaneTilt,
	PencilSimple,
	Signature,
	Translate,
	WarningCircle,
	X,
	type Icon,
} from "@phosphor-icons/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import * as React from "react";

import type { AdminManifest } from "../../lib/api/client.js";
import {
	fetchContent,
	fetchTranslations,
	getPreviewUrl,
	publishContent,
	scheduleContent,
	unscheduleContent,
} from "../../lib/api/content.js";
import type { CurrentUser } from "../../lib/api/current-user.js";
import {
	formatTimeAgo,
	formatTimeUntil,
	type CalendarDisplay,
	type CalendarItem,
	type CalendarState,
} from "../../lib/calendar.js";
import { contentUrl } from "../../lib/url.js";
import { cn } from "../../lib/utils.js";
import { getLocaleLabel } from "../../locales/index.js";
import { getMutationError } from "../DialogError.js";
import { PublishingScheduleDialog } from "../PublishingDateTimeEditor.js";
import { RouterLinkButton } from "../RouterLinkButton.js";
import {
	CALENDAR_STATE_LABELS,
	CalendarCollectionTag,
	CalendarStateIcon,
} from "./CalendarEntry.js";

// Role levels (matching @emdash-cms/auth)
const ROLE_AUTHOR = 30;
const ROLE_EDITOR = 40;

const STATE_TEXT: Record<CalendarState, string> = {
	published: "text-kumo-success",
	scheduled: "text-kumo-info",
	update: "text-kumo-info",
	overdue: "text-kumo-warning",
};

export interface CalendarEntryPanelProps {
	/** The open entry; undefined closes the panel. */
	item: CalendarItem | undefined;
	display: CalendarDisplay;
	now: number;
	/** Narrow layouts show the panel as a bottom sheet over the page. */
	compact: boolean;
	i18n: AdminManifest["i18n"];
	/** Each collection's public URL pattern, for View live. */
	urlPatterns: Readonly<Record<string, string | undefined>>;
	user: CurrentUser | undefined;
	/** The entry link to focus when the panel closes, if it is still on the page. */
	returnFocus?: React.RefObject<HTMLElement | null>;
	onClose: () => void;
	/** Called after the entry gets a new schedule, with its new time. */
	onRescheduled: (item: CalendarItem, scheduledAt: string) => void;
}

/**
 * An entry's details and publishing actions beside the calendar. On wide
 * layouts the calendar stays usable behind it, so picking another entry
 * switches the panel; on phones it is a modal bottom sheet.
 */
export function CalendarEntryPanel(props: CalendarEntryPanelProps) {
	const { item, compact, returnFocus, onClose } = props;
	// The panel keeps its content while it slides out.
	const [shown, setShown] = React.useState(item);
	if (item && item !== shown) setShown(item);

	return (
		<Dialog.Root
			open={Boolean(item)}
			modal={compact}
			disablePointerDismissal={!compact}
			onOpenChange={(open) => {
				if (!open) onClose();
			}}
		>
			<Dialog.Portal>
				{compact && (
					<Dialog.Backdrop className="fixed inset-0 bg-kumo-recessed opacity-80 transition-opacity duration-200 data-ending-style:opacity-0 data-starting-style:opacity-0 motion-reduce:transition-none" />
				)}
				<Dialog.Popup
					finalFocus={() => (returnFocus?.current?.isConnected ? returnFocus.current : true)}
					className={cn(
						"fixed flex flex-col bg-kumo-base text-kumo-default shadow-xl outline-none transition-transform duration-200 ease-out motion-reduce:transition-none",
						compact
							? "inset-x-0 bottom-0 max-h-[85dvh] max-w-none! rounded-t-xl data-ending-style:translate-y-full data-starting-style:translate-y-full"
							: "end-0 top-0 h-full w-full max-w-md border-s border-kumo-line data-ending-style:ltr:translate-x-full data-ending-style:rtl:-translate-x-full data-starting-style:ltr:translate-x-full data-starting-style:rtl:-translate-x-full",
					)}
				>
					{shown && <CalendarEntryPanelContent key={shown.key} {...props} item={shown} />}
				</Dialog.Popup>
			</Dialog.Portal>
		</Dialog.Root>
	);
}

function CalendarEntryPanelContent({
	item,
	display,
	now,
	compact,
	i18n,
	urlPatterns,
	user,
	onClose,
	onRescheduled,
}: CalendarEntryPanelProps & { item: CalendarItem }) {
	const { t } = useLingui();
	const queryClient = useQueryClient();
	const toastManager = Toast.useToastManager();
	const [scheduleOpen, setScheduleOpen] = React.useState(false);
	const [previewing, setPreviewing] = React.useState(false);

	const locale = i18n ? item.locale : undefined;
	const details = useQuery({
		queryKey: ["content", item.collection, item.id, { locale }],
		queryFn: () => fetchContent(item.collection, item.id, { locale }),
		staleTime: 0,
	});
	const translations = useQuery({
		queryKey: ["translations", item.collection, item.id],
		queryFn: () => fetchTranslations(item.collection, item.id),
		enabled: display.showLocale,
	});

	const entry = details.data;
	const canPublish = Boolean(
		user &&
		entry &&
		(user.role >= ROLE_EDITOR || (user.role >= ROLE_AUTHOR && entry.authorId === user.id)),
	);
	const scheduled = item.kind === "scheduled";
	const title = item.title;
	const editorLink = {
		to: "/content/$collection/$id",
		params: { collection: item.collection, id: item.id },
		search: { locale: item.locale },
	} as const;

	const refresh = () => {
		void queryClient.invalidateQueries({ queryKey: ["calendar"] });
		void queryClient.invalidateQueries({ queryKey: ["content", item.collection] });
		void queryClient.invalidateQueries({ queryKey: ["dashboard-stats"] });
	};
	const reportError = (errorTitle: string, error: unknown) => {
		toastManager.add({ title: errorTitle, description: getMutationError(error), type: "error" });
	};

	const publish = useMutation({
		mutationFn: () =>
			publishContent(item.collection, item.id, { locale: item.locale, _rev: entry?._rev }),
		onSuccess: () => {
			refresh();
			toastManager.add({ title: t`Published`, description: t`${title} is now live.` });
			onClose();
		},
		onError: (error) => reportError(t`Could not publish`, error),
	});
	const unschedule = useMutation({
		mutationFn: () => unscheduleContent(item.collection, item.id, { locale: item.locale }),
		onSuccess: () => {
			refresh();
			toastManager.add({
				title: t`Schedule removed`,
				description:
					item.status === "published"
						? t`The scheduled changes to ${title} stay as a draft.`
						: t`${title} is a draft again.`,
			});
			onClose();
		},
		onError: (error) => reportError(t`Could not remove the schedule`, error),
	});
	const reschedule = useMutation({
		mutationFn: (scheduledAt: string) =>
			scheduleContent(item.collection, item.id, scheduledAt, { locale: item.locale }),
		onSuccess: (_changed, scheduledAt) => {
			refresh();
			const when = display.formatDateTime(Date.parse(scheduledAt));
			toastManager.add({ title: t`Rescheduled`, description: t`${title} now goes live ${when}.` });
			onRescheduled(item, scheduledAt);
		},
	});

	const openPreview = async () => {
		setPreviewing(true);
		try {
			const result = await getPreviewUrl(item.collection, item.id);
			const fallback = contentUrl(
				item.collection,
				entry?.slug || item.id,
				urlPatterns[item.collection],
				{
					locale: item.locale,
					i18n,
					id: item.id,
					date: entry?.publishedAt,
				},
			);
			window.open(result?.url ?? fallback, "_blank", "noopener,noreferrer");
		} finally {
			setPreviewing(false);
		}
	};
	const liveUrl =
		item.state === "published" && entry?.slug
			? contentUrl(item.collection, entry.slug, urlPatterns[item.collection], {
					locale: item.locale,
					i18n,
					id: item.id,
					date: entry.publishedAt,
				})
			: undefined;

	const others = (translations.data?.translations ?? []).filter(
		(translation) => translation.locale !== item.locale,
	);
	const bylines = new Intl.ListFormat(display.locale, { type: "conjunction" }).format(
		(entry?.bylines ?? [])
			.toSorted((a, b) => a.sortOrder - b.sortOrder)
			.map((credit) => credit.byline.displayName),
	);
	const time = display.formatDateTime(item.time);
	const viewerTime = display.formatViewerTime(item.time);
	const lateness = formatTimeAgo(now - item.time, display.locale);
	const countdown = formatTimeUntil(item.time - now, display.locale);
	const updatedAt = entry ? Date.parse(entry.updatedAt) : Number.NaN;
	const edited = Number.isNaN(updatedAt)
		? undefined
		: formatTimeAgo(now - updatedAt, display.locale);
	const livePublishedAt = entry?.publishedAt ? Date.parse(entry.publishedAt) : Number.NaN;
	const liveSince = Number.isNaN(livePublishedAt)
		? undefined
		: display.formatDateTime(livePublishedAt);

	return (
		<>
			{compact && (
				<span
					aria-hidden="true"
					className="mx-auto mt-2 h-1 w-10 shrink-0 rounded-full bg-kumo-fill"
				/>
			)}
			<div className="flex shrink-0 items-center justify-between gap-3 ps-5 pe-3 pt-3 sm:ps-6">
				<CalendarCollectionTag slug={item.collection} display={display} />
				<Dialog.Close
					render={
						<Button
							variant="ghost"
							shape="square"
							size="sm"
							aria-label={t`Close`}
							icon={<X aria-hidden="true" />}
						/>
					}
				/>
			</div>

			<div className="flex-1 overflow-y-auto px-5 pt-3 pb-6 sm:px-6">
				<Dialog.Title
					dir="auto"
					className="text-2xl leading-tight font-semibold tracking-tight break-words"
				>
					{title}
				</Dialog.Title>

				<dl className="mt-5 grid grid-cols-[minmax(0,8rem)_minmax(0,1fr)] gap-x-3 gap-y-3 text-sm">
					<PanelProperty icon={CircleHalf} label={t`State`}>
						<span
							className={cn("inline-flex items-center gap-1.5 font-medium", STATE_TEXT[item.state])}
						>
							<CalendarStateIcon state={item.state} />
							{t(CALENDAR_STATE_LABELS[item.state])}
						</span>
					</PanelProperty>
					<PanelProperty
						icon={Clock}
						label={
							scheduled
								? item.state === "overdue"
									? t`Was due`
									: t`Goes live`
								: t(CALENDAR_STATE_LABELS.published)
						}
					>
						<span className="tabular-nums">{time}</span>
						{display.viewerZoneDiffers && (
							<span className="block text-xs text-kumo-subtle tabular-nums">
								{t`Your time: ${viewerTime}`}
							</span>
						)}
					</PanelProperty>
					{display.showLocale && (
						<PanelProperty icon={Translate} label={t`Locale`}>
							<span className="inline-flex items-center gap-1.5">
								{getLocaleLabel(item.locale)}
								<LocaleCode locale={item.locale} />
							</span>
							{others.length > 0 && (
								<span className="mt-1 flex flex-wrap items-center gap-1 text-xs text-kumo-subtle">
									{t`Translations:`}
									{others.map((translation) => (
										<span key={translation.id}>
											<LocaleCode locale={translation.locale} />
											<span className="sr-only">{getLocaleLabel(translation.locale)}</span>
										</span>
									))}
								</span>
							)}
						</PanelProperty>
					)}
					{bylines && (
						<PanelProperty icon={Signature} label={t`Bylines`}>
							{bylines}
						</PanelProperty>
					)}
					<PanelProperty icon={ClockCounterClockwise} label={t`Last edited`}>
						{details.isPending ? <SkeletonLine minWidth={30} maxWidth={45} /> : (edited ?? "—")}
					</PanelProperty>
				</dl>

				{details.isError && (
					<p className="mt-4 text-sm text-kumo-danger">{t`Could not load this entry's details.`}</p>
				)}

				{scheduled && (
					<>
						<hr className="my-6 border-kumo-line" />
						<h3 className="mb-4 text-sm font-semibold">{t`Publishing`}</h3>
						{item.state === "overdue" && (
							<p className="flex gap-2.5 rounded-md bg-kumo-warning-tint px-3 py-2.5 text-sm leading-5">
								<WarningCircle
									aria-hidden="true"
									className="mt-0.5 size-4 shrink-0 text-kumo-warning"
								/>
								<span>
									{t`This entry was due ${lateness} but hasn't published. Scheduled publishing may not be running.`}
								</span>
							</p>
						)}
						{item.state === "scheduled" && (
							<PanelTimeline
								steps={[
									{ icon: CircleDashed, tone: "neutral", title: t`Draft` },
									{
										icon: CalendarDots,
										tone: "info",
										title: t`Scheduled`,
										detail: t`Goes live ${countdown}`,
									},
								]}
							/>
						)}
						{item.state === "update" && (
							<PanelTimeline
								steps={[
									{
										icon: CheckCircle,
										tone: "success",
										title: t`Live version`,
										detail: liveSince && t`Published ${liveSince}`,
									},
									{
										icon: ArrowsClockwise,
										tone: "info",
										title: t`Scheduled changes`,
										detail: t`Go live ${countdown}`,
									},
								]}
							/>
						)}
						{canPublish && (
							<div className="mt-5 flex flex-wrap gap-2">
								{item.state === "overdue" && (
									<Button
										variant="primary"
										icon={<PaperPlaneTilt aria-hidden="true" className="rtl:-scale-x-100" />}
										loading={publish.isPending}
										disabled={unschedule.isPending}
										onClick={() => publish.mutate()}
									>
										{t`Publish now`}
									</Button>
								)}
								<Button
									variant="secondary"
									icon={<CalendarDots aria-hidden="true" />}
									disabled={publish.isPending || unschedule.isPending}
									onClick={() => setScheduleOpen(true)}
								>
									{t`Reschedule`}
								</Button>
								<Button
									variant="secondary-destructive"
									loading={unschedule.isPending}
									disabled={publish.isPending}
									onClick={() => unschedule.mutate()}
								>
									{t`Remove schedule`}
								</Button>
							</div>
						)}
					</>
				)}
			</div>

			<div className="flex shrink-0 flex-wrap items-center gap-2 border-t border-kumo-line px-5 py-3 sm:px-6">
				<RouterLinkButton
					{...editorLink}
					variant="secondary"
					icon={<PencilSimple aria-hidden="true" />}
				>
					{t`Open in editor`}
				</RouterLinkButton>
				{scheduled && (
					<Button
						variant="secondary"
						icon={<Eye aria-hidden="true" />}
						loading={previewing}
						onClick={() => void openPreview()}
					>
						{item.state === "update" ? t`Preview changes` : t`Preview`}
					</Button>
				)}
				{liveUrl && (
					<LinkButton
						href={liveUrl}
						external
						variant="secondary"
						icon={<ArrowSquareOut aria-hidden="true" className="rtl:-scale-x-100" />}
					>
						{t`View live`}
					</LinkButton>
				)}
			</div>

			{scheduled && canPublish && (
				<PublishingScheduleDialog
					open={scheduleOpen}
					entryKey={item.key}
					scheduledAt={item.at}
					isLive={item.status === "published"}
					isPending={reschedule.isPending}
					onOpenChange={setScheduleOpen}
					onSchedule={async (scheduledAt) => {
						await reschedule.mutateAsync(scheduledAt);
					}}
				/>
			)}
		</>
	);
}

function PanelProperty({
	icon: PropertyIcon,
	label,
	children,
}: {
	icon: Icon;
	label: string;
	children: React.ReactNode;
}) {
	return (
		<>
			<dt className="flex items-start gap-2 text-kumo-subtle">
				<span className="flex h-lh shrink-0 items-center">
					<PropertyIcon aria-hidden="true" className="size-4" />
				</span>
				<span className="min-w-0">{label}</span>
			</dt>
			<dd className="min-w-0 break-words">{children}</dd>
		</>
	);
}

function LocaleCode({ locale }: { locale: string }) {
	return (
		<span
			aria-hidden="true"
			className="rounded-sm bg-kumo-fill px-1 text-[10px] leading-4 font-semibold tracking-wide text-kumo-subtle uppercase"
		>
			{locale}
		</span>
	);
}

type PanelTone = "neutral" | "info" | "success";

const TONE_TINTS: Record<PanelTone, string> = {
	neutral: "bg-kumo-fill text-kumo-subtle",
	info: "bg-kumo-info-tint text-kumo-info",
	success: "bg-kumo-success-tint text-kumo-success",
};

function PanelTimeline({
	steps,
}: {
	steps: ReadonlyArray<{ icon: Icon; tone: PanelTone; title: string; detail?: string | false }>;
}) {
	return (
		<ol className="grid">
			{steps.map((step, index) => {
				const StepIcon = step.icon;
				return (
					<li
						key={step.title}
						className="relative grid grid-cols-[1.5rem_minmax(0,1fr)] gap-3 pb-5 last:pb-0"
					>
						{index < steps.length - 1 && (
							<span
								aria-hidden="true"
								className="absolute start-3 top-7 bottom-1 w-px -translate-x-1/2 bg-kumo-line rtl:translate-x-1/2"
							/>
						)}
						<span
							aria-hidden="true"
							className={cn("grid size-6 place-items-center rounded-full", TONE_TINTS[step.tone])}
						>
							<StepIcon className="size-3.5" />
						</span>
						<span className="grid gap-0.5 text-sm">
							<span className="leading-6 font-medium">{step.title}</span>
							{step.detail && <span className="text-kumo-subtle">{step.detail}</span>}
						</span>
					</li>
				);
			})}
		</ol>
	);
}
