// src/lib/calendar/CalendarMonth.svelte
<script lang="ts">
  // EmDash1.1.0 CalendarMonth placement/folding/reservation/picker behavior, pin913cb1bb; MIT.
  import { tick } from 'svelte';
  import { format } from 'date-fns';
  import { getDayPickerLocale } from '../ui/date-time-locales.ts';
  import { isMonthCutOff, shiftDay, dayKeyToUTC, type CalendarDisplay, type CalendarItem } from './calendar.ts';
  import Entry from './CalendarEntry.svelte';
  import DayList from './CalendarDayList.svelte';
  import type { CalendarSelectHandler } from './ui-types.ts';
  let { month, gridDays, days, unfilteredDays, today, now, display, loading, loadedThrough, compact=false, selectedKey, onSelect, onMonthChange, onClearFilters }: {
    month:string;gridDays:readonly string[];days:ReadonlyMap<string,CalendarItem[]>;unfilteredDays?:ReadonlyMap<string,CalendarItem[]>;
    today:string;now:number;display:CalendarDisplay;loading?:boolean;loadedThrough?:string;compact?:boolean;selectedKey?:string;
    onSelect?:CalendarSelectHandler;onMonthChange:(month:string)=>void;onClearFilters?:()=>void;
  }=$props();
  const weeks=$derived(Array.from({length:Math.ceil(gridDays.length/7)},(_,week)=>gridDays.slice(week*7,week*7+7)));
  let picked=$state<string>(), pickedMonth=$state<string>(), focusDay=$state<string>(), popover=$state<string>(), moreTrigger=$state<HTMLButtonElement>();
  $effect(()=>{if(pickedMonth!==month){pickedMonth=month;picked=undefined;}});
  $effect(()=>{if(focusDay?.startsWith(month)){const day=focusDay;void tick().then(()=>document.querySelector<HTMLButtonElement>(`[data-calendar-day="${day}"]`)?.focus());}});
  const firstWithEntries=(map:ReadonlyMap<string,CalendarItem[]>)=>[...map.keys()].filter(day=>day.startsWith(month)).toSorted()[0];
  const selected=$derived(picked??(today.startsWith(month)?today:firstWithEntries(unfilteredDays??days)??`${month}-01`));
  const filteredEmpty=$derived(Boolean(onClearFilters)&&!loading&&!(compact?firstWithEntries(days):gridDays.some(day=>days.has(day))));
  const cutOff=$derived(isMonthCutOff(month,loadedThrough));
  const currentItems=$derived(days.get(selected)??[]);
  function nowIndex(items:readonly CalendarItem[]){const index=items.findIndex(item=>item.time>now);return index===-1?items.length:index;}
  function dayLabel(day:string){const d=new Date(dayKeyToUTC(day));const local=new Date(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),12);const label=format(local,'MMMM do, yyyy',{locale:getDayPickerLocale(display.locale)});const count=days.get(day)?.length??0;return count?`${label}, ${count} ${count===1?'entry':'entries'}`:label;}
  function keydown(event:KeyboardEvent,day:string){const step:Record<string,number>={ArrowRight:1,ArrowLeft:-1,ArrowDown:7,ArrowUp:-7};if(!(event.key in step))return;event.preventDefault();const next=shiftDay(day,step[event.key]!);focusDay=next;picked=next;if(!next.startsWith(month))onMonthChange(next.slice(0,7));else void tick().then(()=>document.querySelector<HTMLButtonElement>(`[data-calendar-day="${next}"]`)?.focus());}
  function reservedHeight(week:readonly string[]){return Math.max(112,...week.map(day=>{const items=unfilteredDays?.get(day)??days.get(day)??[];const room=items.toSorted((a,b)=>Number(a.state==='published')-Number(b.state==='published')).slice(0,4);return 32+room.reduce((height,item)=>height+(item.state==='published'?24:52),0);}));}
</script>
{#snippet notice()}<div class="notice"><p>{cutOff?'No loaded entries match these filters':'No entries match these filters'}</p><button type="button" onclick={onClearFilters}>Clear filters</button></div>{/snippet}
{#snippet cellEntries(day:string,items:readonly CalendarItem[])}
  {@const visible=items.length>4?items.slice(0,3):items}
  {@const nowAt=day===today?nowIndex(items):undefined}
  {@const lineAt=nowAt===undefined||nowAt<=visible.length?nowAt:nowAt===items.length?items.length:undefined}
  <ul aria-label={display.fullDate(day)}>
    {#each visible as item,index(item.key)}{#if index===lineAt}<li aria-hidden="true" class="now-line"></li>{/if}<li><Entry {item} {display} {now} {onSelect} chip selected={item.key===selectedKey}/></li>{/each}
    {#if lineAt===visible.length}<li aria-hidden="true" class="now-line"></li>{/if}
    {#if visible.length<items.length}<li><button type="button" aria-label={`${items.length-3} more ${items.length-3===1?'entry':'entries'} on ${display.fullDate(day)}`} onclick={event=>{moreTrigger=event.currentTarget;popover=day;}}>+{items.length-3} more</button></li>{/if}
    {#if visible.length<items.length&&lineAt===items.length}<li aria-hidden="true" class="now-line"></li>{/if}
  </ul>
{/snippet}
<div class="month">
<table aria-label={display.monthTitle(month)}><thead><tr>{#each weeks[0]??[] as day}<th scope="col" aria-label={display.weekday(day)}>{display.weekdayShort(day)}</th>{/each}</tr></thead>
<tbody>{#each weeks as week(week[0])}<tr style:height={!compact?`${reservedHeight(week)}px`:undefined}>{#each week as day(day)}
  <td class:outside={!day.startsWith(month)} class:weekend={display.isWeekend(day)} aria-current={day===today?'date':undefined}>
  {#if compact}
    {#if day.startsWith(month)}<button type="button" data-calendar-day={day} aria-label={dayLabel(day)} aria-pressed={selected===day} tabindex={(focusDay??selected)===day?0:-1} onclick={()=>picked=day} onkeydown={event=>keydown(event,day)}>{display.dayNumber(day)}<span aria-hidden="true" class="dots">{#each (days.get(day)??[]).slice(0,3) as item}<i class={item.state}></i>{/each}{#if (days.get(day)?.length??0)>3}+{/if}</span></button>{/if}
  {:else}<div class="date">{day.endsWith('-01')?display.monthDayShort(day):display.dayNumber(day)}</div>
    {#if (days.get(day)?.length??0)>0}{@render cellEntries(day,days.get(day)!)}{:else if loadedThrough!==undefined&&day>=loadedThrough}<p class="not-loaded">Not loaded</p>{/if}
  {/if}</td>{/each}</tr>{/each}</tbody></table>
{#if !compact&&filteredEmpty}{@render notice()}{/if}</div>
{#if compact}<section><h3>{display.weekday(selected)} <span>{display.monthDay(selected)}</span></h3>
  {#if loading}<p role="status">Loading calendar…</p>{:else if filteredEmpty}{@render notice()}
  {:else if currentItems.length}<DayList items={currentItems} {display} {now} label={display.fullDate(selected)} nowAt={selected===today?nowIndex(currentItems):undefined} {selectedKey} {onSelect}/>
  {:else}<p>{loadedThrough&&selected>=loadedThrough?"This day wasn't loaded. The range has more entries than the calendar can show.":'Nothing on this day.'}</p>{/if}
</section>{/if}
{#if popover}<div role="dialog" aria-label={display.fullDate(popover)} tabindex="-1" class="popover" onkeydown={event=>{if(event.key==='Escape'){popover=undefined;moreTrigger?.focus();}}}>
  <h3>{display.fullDate(popover)}</h3><DayList items={days.get(popover)??[]} {display} {now} label={display.fullDate(popover)} nowAt={popover===today?nowIndex(days.get(popover)??[]):undefined} {selectedKey}
    onSelect={onSelect?(item,element)=>{popover=undefined;onSelect?.(item,moreTrigger??element);}:undefined}/>
  <button type="button" onclick={()=>{popover=undefined;moreTrigger?.focus();}}>Close</button></div>{/if}
<style>
  .month{position:relative;border:1px solid var(--border,#ddd);border-radius:.5rem;overflow:hidden;}table{width:100%;table-layout:fixed;border-collapse:collapse;}th{font-size:.75rem;font-weight:400;text-align:right;padding:.5rem;}td{vertical-align:top;border:1px solid var(--border,#ddd);padding:.25rem;}td.outside,td.weekend{background:var(--muted,#f5f5f5);} .date{text-align:right;height:1.75rem;font-size:.75rem;}ul{list-style:none;padding:0;margin:0;display:grid;gap:4px;}button{font:inherit;color:inherit;background:var(--card,#fff);border:1px solid var(--border,#ddd);padding:.4rem;cursor:pointer;border-radius:.3rem;}[data-calendar-day]{width:100%;min-height:2.75rem;}[aria-pressed="true"]{background:var(--primary,#174bbf);color:white;}.dots{height:.4rem;display:flex;justify-content:center;gap:3px;font-size:.6rem;}i{width:5px;height:5px;background:#337bdb;border-radius:50%;}i.published{background:#329065;}i.overdue{background:#b96800;}.now-line{border-bottom:2px solid #b32929;height:2px;}.notice{padding:1rem;background:var(--card,#fff);display:flex;gap:1rem;align-items:center;justify-content:center;}.month>.notice{position:absolute;inset:0;background:#fffd;}h3{font-size:1rem;}h3 span{font-weight:400;}.popover{position:fixed;z-index:40;left:50%;top:50%;transform:translate(-50%,-50%);background:var(--card,#fff);border:1px solid var(--border,#ddd);box-shadow:0 10px 40px #0003;padding:1rem;width:20rem;max-width:calc(100vw - 2rem);max-height:80vh;overflow:auto;}.not-loaded{font-size:.75rem;color:var(--muted-foreground,#666);}button:focus-visible{outline:2px solid var(--ring,#165ccc);outline-offset:2px;}
</style>

// parity/emdash/scheduled-publishing-source/upstream/packages/admin/src/components/calendar/CalendarMonth.tsx
import {
	Badge,
	Button,
	DatePicker,
	LayerCard,
	Popover,
	SkeletonLine,
	TooltipProvider,
} from "@cloudflare/kumo";
import { plural } from "@lingui/core/macro";
import { useLingui } from "@lingui/react/macro";
import { Funnel } from "@phosphor-icons/react";
import * as React from "react";
import type { DayButtonProps } from "react-day-picker";

import {
	isMonthCutOff,
	type CalendarDisplay,
	type CalendarItem,
	type CalendarState,
} from "../../lib/calendar.js";
import { cn } from "../../lib/utils.js";
import { getDayPickerLocale } from "../../locales/day-picker.js";
import { getLocaleDir } from "../../locales/index.js";
import {
	CalendarDayList,
	CalendarEntryChip,
	CalendarNowLine,
	type CalendarSelectHandler,
} from "./CalendarEntry.js";

/** A cell shows every entry up to this many; past it, one fewer plus "+N more". */
const MAX_CHIPS = 4;
const MAX_DOTS = 3;

const DOT_COLORS: Record<CalendarState, string> = {
	published: "bg-kumo-success",
	scheduled: "bg-kumo-info",
	update: "bg-kumo-info",
	overdue: "bg-kumo-warning",
};

interface CalendarMonthProps {
	month: string;
	/** Every day the grid shows, whole weeks from the locale's first weekday. */
	gridDays: readonly string[];
	days: ReadonlyMap<string, CalendarItem[]>;
	/**
	 * Every loaded entry by day, before filters. Cells keep room for any of
	 * these a filter could show, so filtering doesn't move the grid.
	 */
	unfilteredDays?: ReadonlyMap<string, CalendarItem[]>;
	today: string;
	now: number;
	display: CalendarDisplay;
	loading?: boolean;
	/** The last day with loaded entries, when the range has more entries than were loaded. */
	loadedThrough?: string;
	/** Phones get a date picker with the chosen day's entries below it. */
	compact?: boolean;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
	onMonthChange: (month: string) => void;
	/** Filters are on; when they hide every entry, a notice offers to clear them. */
	onClearFilters?: () => void;
}

export function CalendarMonth(props: CalendarMonthProps) {
	return props.compact ? <CalendarMonthPicker {...props} /> : <CalendarMonthGrid {...props} />;
}

/**
 * The entries whose chips take the most room any filter could show at once:
 * raised cards before flat ones, as many as a cell shows unfolded. A folded
 * cell never needs more, since "+N more" is no taller than a flat chip.
 */
function roomiestEntries(items: readonly CalendarItem[]): CalendarItem[] {
	return items
		.toSorted((a, b) => Number(a.state === "published") - Number(b.state === "published"))
		.slice(0, MAX_CHIPS);
}

function nowIndex(items: readonly CalendarItem[], now: number): number {
	const index = items.findIndex((item) => item.time > now);
	return index === -1 ? items.length : index;
}

function CalendarFilteredNotice({
	cutOff,
	onClearFilters,
}: {
	cutOff: boolean;
	onClearFilters: () => void;
}) {
	const { t } = useLingui();
	return (
		<LayerCard className="flex items-center gap-3 px-4 py-3 text-sm shadow-lg">
			<Funnel aria-hidden="true" className="size-4 shrink-0 text-kumo-subtle" />
			<span className="min-w-0">
				{cutOff ? t`No loaded entries match these filters` : t`No entries match these filters`}
			</span>
			<Button variant="secondary" size="sm" onClick={onClearFilters} className="shrink-0">
				{t`Clear filters`}
			</Button>
		</LayerCard>
	);
}

function CalendarMonthGrid({
	month,
	gridDays,
	days,
	unfilteredDays,
	today,
	now,
	display,
	loading,
	loadedThrough,
	selectedKey,
	onSelect,
	onClearFilters,
}: CalendarMonthProps) {
	const weeks = React.useMemo(
		() =>
			Array.from({ length: Math.ceil(gridDays.length / 7) }, (_, week) =>
				gridDays.slice(week * 7, week * 7 + 7),
			),
		[gridDays],
	);
	const filteredEmpty =
		Boolean(onClearFilters) && !loading && !gridDays.some((day) => days.has(day));

	return (
		<TooltipProvider delay={400}>
			<div className="relative overflow-hidden rounded-lg border border-kumo-line bg-kumo-base">
				<table className="w-full table-fixed border-collapse">
					<thead>
						<tr>
							{weeks[0]?.map((day) => (
								<th
									key={day}
									scope="col"
									aria-label={display.weekday(day)}
									className="px-2 pt-2 pb-1.5 text-end text-xs font-normal text-kumo-subtle"
								>
									{display.weekdayShort(day)}
								</th>
							))}
						</tr>
					</thead>
					<tbody>
						{weeks.map((week) => (
							<tr key={week[0]}>
								{week.map((day) => (
									<CalendarMonthCell
										key={day}
										day={day}
										items={days.get(day) ?? []}
										reservedItems={unfilteredDays?.get(day)}
										inMonth={day.startsWith(month)}
										loaded={loadedThrough === undefined || day < loadedThrough}
										today={today}
										now={now}
										display={display}
										selectedKey={selectedKey}
										onSelect={onSelect}
									/>
								))}
							</tr>
						))}
					</tbody>
				</table>
				{filteredEmpty &&
					onClearFilters && (
						// An overlay, so showing it doesn't resize the grid.
						<div className="absolute inset-0 flex items-center justify-center bg-radial from-kumo-base/90 via-kumo-base/60 to-kumo-base/30 p-4 backdrop-blur-xs transition-opacity duration-200 starting:opacity-0 motion-reduce:transition-none">
							<CalendarFilteredNotice
								cutOff={loadedThrough !== undefined}
								onClearFilters={onClearFilters}
							/>
						</div>
					)}
			</div>
		</TooltipProvider>
	);
}

interface CalendarMonthCellProps {
	day: string;
	items: readonly CalendarItem[];
	/** The day's entries before filters; the cell keeps room for any of them a filter could show. */
	reservedItems?: readonly CalendarItem[];
	inMonth: boolean;
	/** False from the day the entry cap cut the range off, which may be only partly loaded. */
	loaded: boolean;
	today: string;
	now: number;
	display: CalendarDisplay;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
}

function CalendarMonthCell({
	day,
	items,
	reservedItems,
	inMonth,
	loaded,
	today,
	now,
	display,
	selectedKey,
	onSelect,
}: CalendarMonthCellProps) {
	const { t } = useLingui();
	const isToday = day === today;
	// Unfiltered, a cell showing every entry already takes that room.
	const reserveRoom =
		reservedItems !== undefined &&
		(reservedItems.length > MAX_CHIPS || items.length < reservedItems.length);
	const label = day.endsWith("-01") ? display.monthDayShort(day) : display.dayNumber(day);

	return (
		<td
			aria-current={isToday ? "date" : undefined}
			className={cn(
				"border-s border-t border-kumo-line p-1 align-top first:border-s-0",
				(!inMonth || display.isWeekend(day)) && "bg-kumo-elevated",
			)}
		>
			<div className="flex min-h-28 min-w-0 flex-col gap-1">
				<div className="flex justify-end">
					{isToday ? (
						<Badge variant="red" className="h-6 min-w-6 justify-center px-1.5 tabular-nums">
							{label}
						</Badge>
					) : (
						<span
							className={cn(
								"inline-flex h-6 min-w-6 items-center justify-center px-1.5 text-xs tabular-nums",
								!inMonth
									? "text-kumo-inactive"
									: day < today
										? "text-kumo-subtle"
										: "text-kumo-default",
							)}
						>
							{label}
						</span>
					)}
				</div>
				<div className="grid min-w-0">
					{reserveRoom && (
						<div className="invisible col-start-1 row-start-1 min-w-0">
							<CalendarCellEntries
								day={day}
								items={roomiestEntries(reservedItems)}
								today={today}
								now={now}
								display={display}
							/>
						</div>
					)}
					<div className="col-start-1 row-start-1 min-w-0">
						{items.length > 0 && (
							<CalendarCellEntries
								day={day}
								items={items}
								today={today}
								now={now}
								display={display}
								selectedKey={selectedKey}
								onSelect={onSelect}
							/>
						)}
						{items.length === 0 && !loaded && (
							<p className="px-1 text-xs text-kumo-inactive">{t`Not loaded`}</p>
						)}
					</div>
				</div>
			</div>
		</td>
	);
}

function CalendarCellEntries({
	day,
	items,
	today,
	now,
	display,
	selectedKey,
	onSelect,
}: {
	day: string;
	items: readonly CalendarItem[];
	today: string;
	now: number;
	display: CalendarDisplay;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
}) {
	const visible = items.length > MAX_CHIPS ? items.slice(0, MAX_CHIPS - 1) : items;
	const nowAt = day === today ? nowIndex(items, now) : undefined;
	// The line goes among the chips, or after "+N more" once every entry is past;
	// when the present falls among the folded entries, only the popover shows it.
	const lineAt =
		nowAt === undefined || nowAt <= visible.length
			? nowAt
			: nowAt === items.length
				? items.length
				: undefined;
	const nowLine = (
		<li key="now" aria-hidden="true" className="px-0.5">
			<CalendarNowLine />
		</li>
	);

	return (
		<ul aria-label={display.fullDate(day)} className="@container grid min-w-0 gap-1">
			{visible.map((item, index) => (
				<React.Fragment key={item.key}>
					{index === lineAt && nowLine}
					<li className="grid min-w-0">
						<CalendarEntryChip
							item={item}
							display={display}
							now={now}
							selected={item.key === selectedKey}
							onSelect={onSelect}
						/>
					</li>
				</React.Fragment>
			))}
			{lineAt === visible.length && nowLine}
			{visible.length < items.length && (
				<li>
					<CalendarMorePopover
						day={day}
						items={items}
						display={display}
						now={now}
						nowAt={nowAt}
						selectedKey={selectedKey}
						onSelect={onSelect}
					/>
				</li>
			)}
			{visible.length < items.length && lineAt === items.length && nowLine}
		</ul>
	);
}

interface CalendarMorePopoverProps {
	day: string;
	items: readonly CalendarItem[];
	display: CalendarDisplay;
	now: number;
	nowAt?: number;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
}

function CalendarMorePopover({
	day,
	items,
	display,
	now,
	nowAt,
	selectedKey,
	onSelect,
}: CalendarMorePopoverProps) {
	const [open, setOpen] = React.useState(false);
	const triggerRef = React.useRef<HTMLButtonElement>(null);
	const hidden = items.length - (MAX_CHIPS - 1);
	const date = display.fullDate(day);

	return (
		<Popover open={open} onOpenChange={setOpen}>
			<Popover.Trigger
				render={
					<Button
						ref={triggerRef}
						variant="ghost"
						size="xs"
						className="w-full justify-start px-1.5 text-kumo-subtle"
						aria-label={plural(hidden, {
							one: `# more entry on ${date}`,
							other: `# more entries on ${date}`,
						})}
					/>
				}
			>
				{plural(hidden, { one: "+# more", other: "+# more" })}
			</Popover.Trigger>
			<Popover.Content className="w-80 max-w-[calc(100vw-2rem)] p-2" align="start">
				<Popover.Title className="px-2 pt-1 pb-2 text-sm font-semibold">{date}</Popover.Title>
				<CalendarDayList
					items={items}
					display={display}
					now={now}
					label={date}
					nowAt={nowAt}
					selectedKey={selectedKey}
					onSelect={
						onSelect &&
						((item, element) => {
							setOpen(false);
							// The popover's entries unmount with it, so focus returns to "+N more".
							onSelect(item, triggerRef.current ?? element);
						})
					}
					className="max-h-80 overflow-y-auto"
				/>
			</Popover.Content>
		</Popover>
	);
}

/** Each day's entry states, read by the picker's day buttons. */
const DayStatesContext = React.createContext<ReadonlyMap<string, CalendarState[]>>(new Map());

/** Day buttons sized for touch, with today in the grid's red. */
const PICKER_STYLE = {
	"--rdp-day-height": "2.75rem",
	"--rdp-day_button-height": "2.5rem",
	"--rdp-day_button-width": "min(2.5rem, 100%)",
	"--rdp-today-color": "var(--color-kumo-danger)",
} as React.CSSProperties;

function pad(value: number): string {
	return String(value).padStart(2, "0");
}

/** The picker works in local dates; noon keeps a day key on its date across DST changes. */
function dayKeyToLocalDate(day: string): Date {
	const [year = 1970, month = 1, date = 1] = day.split("-").map(Number);
	return new Date(year, month - 1, date, 12);
}

function localDateToDayKey(date: Date): string {
	return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
}

function CalendarDayButton({ day, modifiers, children, className, ...props }: DayButtonProps) {
	const { t } = useLingui();
	const ref = React.useRef<HTMLButtonElement>(null);
	const states = React.useContext(DayStatesContext).get(localDateToDayKey(day.date)) ?? [];

	React.useEffect(() => {
		if (modifiers.focused) ref.current?.focus();
	}, [modifiers.focused]);

	const dayLabel = props["aria-label"] ?? "";
	const entries = plural(states.length, { one: "# entry", other: "# entries" });

	return (
		<button
			ref={ref}
			{...props}
			className={cn(
				className,
				// Kumo's unlayered picker styles leave the button at the start of the wider column.
				"!mx-auto",
				// Kumo's red badge keeps white text in both themes; the inverse text tokens turn dark.
				modifiers.today && modifiers.selected && "!bg-kumo-badge-red !text-white",
			)}
			aria-label={states.length > 0 ? t`${dayLabel}, ${entries}` : dayLabel || undefined}
		>
			<span className="flex flex-col items-center gap-0.5 leading-none">
				{children}
				<span aria-hidden="true" className="flex h-1.5 items-center gap-0.5">
					{states.slice(0, MAX_DOTS).map((state, index) => (
						<span
							key={index}
							className={cn(
								"size-1.5 rounded-full",
								modifiers.selected ? "bg-current" : DOT_COLORS[state],
							)}
						/>
					))}
					{states.length > MAX_DOTS && (
						<span
							className={cn(
								"text-[10px] leading-none font-semibold",
								!modifiers.selected && "text-kumo-subtle",
							)}
						>
							+
						</span>
					)}
				</span>
			</span>
		</button>
	);
}

function CalendarMonthPicker({
	month,
	days,
	unfilteredDays,
	today,
	now,
	display,
	loading,
	loadedThrough,
	selectedKey,
	onSelect,
	onMonthChange,
	onClearFilters,
}: CalendarMonthProps) {
	const { t, i18n } = useLingui();
	const headingId = React.useId();
	const [picked, setPicked] = React.useState<string>();
	const [pickedMonth, setPickedMonth] = React.useState(month);
	if (pickedMonth !== month) {
		setPickedMonth(month);
		setPicked(undefined);
	}

	const states = React.useMemo(
		() => new Map(Array.from(days, ([day, items]) => [day, items.map((item) => item.state)])),
		[days],
	);
	const firstWithEntries = (map: ReadonlyMap<string, CalendarItem[]>) =>
		[...map.keys()].filter((day) => day.startsWith(month)).toSorted()[0];
	// The default day comes from every entry, so filtering doesn't move the selection.
	const firstDay = firstWithEntries(unfilteredDays ?? days);
	const selected = picked ?? (today.startsWith(month) ? today : (firstDay ?? `${month}-01`));
	const filteredEmpty = Boolean(onClearFilters) && !loading && !firstWithEntries(days);
	const items = days.get(selected) ?? [];

	return (
		<div className="grid gap-4">
			<DayStatesContext.Provider value={states}>
				<DatePicker
					mode="single"
					required
					selected={dayKeyToLocalDate(selected)}
					onChange={(date) => setPicked(localDateToDayKey(date))}
					month={dayKeyToLocalDate(`${month}-01`)}
					onMonthChange={(date) => onMonthChange(localDateToDayKey(date).slice(0, 7))}
					today={dayKeyToLocalDate(today)}
					hideNavigation
					showOutsideDays={false}
					animate={false}
					locale={getDayPickerLocale(i18n.locale)}
					dir={getLocaleDir(i18n.locale)}
					components={{ DayButton: CalendarDayButton }}
					style={PICKER_STYLE}
					className="w-full rounded-lg border border-kumo-line p-2"
					classNames={{
						month_caption: "sr-only",
						month: "rdp-month !w-full",
						month_grid: "rdp-month_grid !w-full table-fixed",
						months: "rdp-months !w-full !max-w-none",
					}}
				/>
			</DayStatesContext.Provider>
			<section aria-labelledby={headingId} className="grid gap-1">
				<h3
					id={headingId}
					className="flex items-baseline gap-2 border-b border-kumo-line px-2 pb-2 text-base"
				>
					<span className="font-semibold text-kumo-default">{display.weekday(selected)}</span>
					<span className="text-kumo-subtle">{display.monthDay(selected)}</span>
					{selected === today && (
						<Badge variant="red" className="self-center">
							{t`Today`}
						</Badge>
					)}
				</h3>
				{loading ? (
					<div aria-hidden="true" className="grid gap-3 px-2 py-2">
						<SkeletonLine minWidth={40} maxWidth={70} />
						<SkeletonLine minWidth={30} maxWidth={60} />
					</div>
				) : filteredEmpty && onClearFilters ? (
					<div className="py-2">
						<CalendarFilteredNotice
							cutOff={isMonthCutOff(month, loadedThrough)}
							onClearFilters={onClearFilters}
						/>
					</div>
				) : items.length > 0 ? (
					<CalendarDayList
						items={items}
						display={display}
						now={now}
						label={display.fullDate(selected)}
						nowAt={selected === today ? nowIndex(items, now) : undefined}
						selectedKey={selectedKey}
						onSelect={onSelect}
					/>
				) : (
					<p className="px-2 py-3 text-sm text-kumo-subtle">
						{loadedThrough && selected >= loadedThrough
							? t`This day wasn't loaded. The range has more entries than the calendar can show.`
							: t`Nothing on this day.`}
					</p>
				)}
			</section>
		</div>
	);
}
