// src/lib/calendar/CalendarAgenda.svelte
<script lang="ts">
  import { useCalendarMessages } from './message-context.svelte.ts';
  const t = useCalendarMessages();
  // EmDash1.1.0 CalendarAgenda whole placement/collapse behavior, pin913cb1bb; MIT.
  import { isMonthCutOff, shiftDay, type CalendarDisplay, type CalendarItem } from './calendar.ts';
  import DayList from './CalendarDayList.svelte';
  import type { CalendarSelectHandler } from './ui-types.ts';
  let { month, days, today, now, display, loading, loadedThrough, onClearFilters, selectedKey, onSelect }: {
    month:string; days:ReadonlyMap<string,CalendarItem[]>; today:string; now:number; display:CalendarDisplay;
    loading?:boolean; loadedThrough?:string; onClearFilters?:()=>void; selectedKey?:string; onSelect?:CalendarSelectHandler;
  } = $props();
  let showEarlier = $state<boolean>();
  const headingPrefix=$props.id(),tomorrow=$derived(shiftDay(today,1));
  const cutOff = $derived(isMonthCutOff(month, loadedThrough));
  const keys = $derived([...days.keys()].filter(day=>day.startsWith(month)).toSorted());
  const current = $derived(today.startsWith(month));
  const earlier = $derived(current ? keys.filter(day=>day<today) : []);
  const earlierCount = $derived(earlier.reduce((n,day)=>n+(days.get(day)?.length??0),0));
  const expanded = $derived(showEarlier ?? earlier.some(day=>days.get(day)?.some(item=>item.state==='overdue')));
  const shown = $derived(expanded || !current ? keys : keys.filter(day=>day>=today));
  const todayItems = $derived(current ? days.get(today) : undefined);
  const firstUpcoming = $derived(todayItems?.findIndex(item=>item.time>now)??-1);
  const nowAt = $derived(todayItems ? firstUpcoming === -1 ? todayItems.length : firstUpcoming : undefined);
  const nextDay = $derived(current && !todayItems ? shown.find(day=>day>today) : undefined);
  const nothingAfter = $derived(current && !cutOff && !keys.some(day=>days.get(day)?.some(item=>item.time>now)));
</script>
{#if loading}<p role="status">Loading calendar…</p>
{:else if keys.length === 0}
  <div class="empty"><h3>{cutOff ? onClearFilters ? t("No loaded entries match these filters") : t("This month wasn't loaded") : onClearFilters ? t("No entries match these filters") : t("Nothing published or scheduled in {monthTitle}",{monthTitle:display.monthTitle(month)})}</h3>
  {#if cutOff}<p>{t("The range has more entries than the calendar can show.")}</p>{:else if !onClearFilters}<p>{t("Scheduled entries appear here with their publish time.")}</p>{/if}
  {#if onClearFilters}<button type="button" onclick={onClearFilters}>{t("Clear filters")}</button>{/if}</div>
{:else}
  {#if earlierCount > 0}<button class="earlier" type="button" aria-expanded={expanded} onclick={()=>showEarlier=!expanded}>{expanded ? t("Hide earlier entries") : t("{earlierCount, plural, one {Show # earlier entry} other {Show # earlier entries}}",{earlierCount})}</button>{/if}
  {#each shown as day (day)}
    {#if day === nextDay}<p class="now">{t("Now · {time}",{time:display.formatTime(now)})}</p>{/if}
    <section aria-labelledby={`${headingPrefix}-${day}`}><h3 id={`${headingPrefix}-${day}`}>{display.weekday(day)} <span>{display.monthDay(day)}</span>{#if day===today} <strong>{t("Today")}</strong>{:else if day===tomorrow} <strong>{t("Tomorrow")}</strong>{/if}</h3><DayList items={days.get(day)??[]} {display} {now} label={display.fullDate(day)} nowAt={day===today?nowAt:undefined} {selectedKey} {onSelect}/></section>
  {/each}
  {#if current && !todayItems && !nextDay}<p class="now">{t("Now · {time}",{time:display.formatTime(now)})}</p>{/if}
  {#if nothingAfter}<p>{t("Nothing else is scheduled this month.")}</p>{/if}
  {#if cutOff}<p>{t("Later entries weren't loaded. The range has more entries than the calendar can show.")}</p>{/if}
{/if}
<style>section {margin:1.25rem 0;} h3 {font-size:.875rem;margin:0 0 .5rem;padding:0 .5rem;} .now{color:#b32929;border-bottom:2px solid #b32929;padding:.4rem .5rem;font-size:.75rem;} .empty{text-align:center;padding:3rem 1rem;} button{font:inherit;padding:.5rem .75rem;cursor:pointer;} .earlier{background:transparent;border:0;}</style>

// parity/emdash/scheduled-publishing-source/upstream/packages/admin/src/components/calendar/CalendarAgenda.tsx
import { Badge, Button, Empty, SkeletonLine } from "@cloudflare/kumo";
import { plural } from "@lingui/core/macro";
import { useLingui } from "@lingui/react/macro";
import { CalendarBlank, CaretDown } from "@phosphor-icons/react";
import * as React from "react";

import {
	isMonthCutOff,
	shiftDay,
	type CalendarDisplay,
	type CalendarItem,
} from "../../lib/calendar.js";
import { CaretNext } from "../ArrowIcons.js";
import { CalendarDayList, CalendarNowLine, type CalendarSelectHandler } from "./CalendarEntry.js";

interface CalendarAgendaProps {
	month: string;
	days: ReadonlyMap<string, CalendarItem[]>;
	today: string;
	now: number;
	display: CalendarDisplay;
	loading?: boolean;
	/** The last day with loaded entries, when the range has more entries than were loaded. */
	loadedThrough?: string;
	/** Filters are hiding entries; the empty state offers to clear them. */
	onClearFilters?: () => void;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
}

/**
 * The month as a list of days. In the current month, days before today
 * start collapsed and a red line marks the present.
 */
export function CalendarAgenda({
	month,
	days,
	today,
	now,
	display,
	loading,
	loadedThrough,
	onClearFilters,
	selectedKey,
	onSelect,
}: CalendarAgendaProps) {
	const { t } = useLingui();
	const [showEarlier, setShowEarlier] = React.useState<boolean>();

	if (loading) return <CalendarAgendaSkeleton />;

	const cutOff = isMonthCutOff(month, loadedThrough);
	const keys = [...days.keys()].filter((day) => day.startsWith(month)).toSorted();
	if (keys.length === 0) {
		const monthTitle = display.monthTitle(month);
		return (
			<Empty
				size="sm"
				icon={<CalendarBlank size={32} aria-hidden="true" />}
				title={
					cutOff
						? onClearFilters
							? t`No loaded entries match these filters`
							: t`This month wasn't loaded`
						: onClearFilters
							? t`No entries match these filters`
							: t`Nothing published or scheduled in ${monthTitle}`
				}
				description={
					cutOff
						? t`The range has more entries than the calendar can show.`
						: onClearFilters
							? undefined
							: t`Scheduled entries appear here with their publish time.`
				}
				contents={
					onClearFilters ? (
						<Button variant="secondary" size="sm" onClick={onClearFilters}>
							{t`Clear filters`}
						</Button>
					) : undefined
				}
			/>
		);
	}

	const isCurrentMonth = today.startsWith(month);
	const earlier = isCurrentMonth ? keys.filter((day) => day < today) : [];
	const earlierCount = earlier.reduce((count, day) => count + (days.get(day)?.length ?? 0), 0);
	// Earlier days start expanded while one of them holds an overdue entry.
	const expanded =
		showEarlier ?? earlier.some((day) => days.get(day)?.some((item) => item.state === "overdue"));
	const shown = expanded || !isCurrentMonth ? keys : keys.filter((day) => day >= today);

	const todayItems = isCurrentMonth ? days.get(today) : undefined;
	const firstUpcoming = todayItems?.findIndex((item) => item.time > now) ?? -1;
	const nowAt = todayItems && (firstUpcoming === -1 ? todayItems.length : firstUpcoming);
	const nextDay = isCurrentMonth && !todayItems ? shown.find((day) => day > today) : undefined;
	const nothingAfterNow =
		isCurrentMonth &&
		!cutOff &&
		!keys.some((day) => days.get(day)?.some((item) => item.time > now));
	const time = display.formatTime(now);
	const standaloneNowLine = <CalendarNowLine label={t`Now · ${time}`} className="px-2" />;
	const tomorrow = shiftDay(today, 1);

	return (
		<div className="grid gap-6">
			{earlierCount > 0 && (
				<Button
					variant="ghost"
					size="sm"
					className="justify-self-start text-kumo-subtle"
					aria-expanded={expanded}
					icon={expanded ? <CaretDown aria-hidden="true" /> : <CaretNext aria-hidden="true" />}
					onClick={() => setShowEarlier(!expanded)}
				>
					{expanded
						? t`Hide earlier entries`
						: plural(earlierCount, {
								one: "Show # earlier entry",
								other: "Show # earlier entries",
							})}
				</Button>
			)}
			{shown.map((day) => (
				<React.Fragment key={day}>
					{day === nextDay && standaloneNowLine}
					<CalendarAgendaDay
						day={day}
						items={days.get(day) ?? []}
						relative={day === today ? "today" : day === tomorrow ? "tomorrow" : undefined}
						nowAt={day === today ? nowAt : undefined}
						now={now}
						display={display}
						selectedKey={selectedKey}
						onSelect={onSelect}
					/>
				</React.Fragment>
			))}
			{isCurrentMonth && !todayItems && !nextDay && standaloneNowLine}
			{nothingAfterNow && (
				<p className="px-2 text-sm text-kumo-subtle">{t`Nothing else is scheduled this month.`}</p>
			)}
			{cutOff && (
				<p className="px-2 text-sm text-kumo-subtle">
					{t`Later entries weren't loaded. The range has more entries than the calendar can show.`}
				</p>
			)}
		</div>
	);
}

interface CalendarAgendaDayProps {
	day: string;
	items: readonly CalendarItem[];
	relative?: "today" | "tomorrow";
	nowAt?: number;
	now: number;
	display: CalendarDisplay;
	selectedKey?: string;
	onSelect?: CalendarSelectHandler;
}

function CalendarAgendaDay({
	day,
	items,
	relative,
	nowAt,
	now,
	display,
	selectedKey,
	onSelect,
}: CalendarAgendaDayProps) {
	const { t } = useLingui();
	const headingId = React.useId();

	return (
		<section aria-labelledby={headingId}>
			<h3
				id={headingId}
				className="sticky top-0 z-10 flex items-baseline gap-2 border-b border-kumo-line bg-kumo-elevated px-2 pt-2 pb-2 text-base before:pointer-events-none before:absolute before:inset-x-0 before:bottom-full before:h-6 before:bg-kumo-elevated"
			>
				<span className="font-semibold text-kumo-default">{display.weekday(day)}</span>
				<span className="text-kumo-subtle">{display.monthDay(day)}</span>
				{relative === "today" && (
					<Badge variant="red" className="self-center">
						{t`Today`}
					</Badge>
				)}
				{relative === "tomorrow" && (
					<Badge variant="secondary" className="self-center">
						{t`Tomorrow`}
					</Badge>
				)}
			</h3>
			<CalendarDayList
				items={items}
				display={display}
				now={now}
				label={display.fullDate(day)}
				nowAt={nowAt}
				selectedKey={selectedKey}
				onSelect={onSelect}
				className="mt-1"
			/>
		</section>
	);
}

function CalendarAgendaSkeleton() {
	return (
		<div aria-hidden="true" className="grid gap-5">
			{[0, 1].map((section) => (
				<div key={section} className="grid gap-3">
					<div className="border-b border-kumo-line px-2 pb-2">
						<SkeletonLine minWidth={18} maxWidth={28} />
					</div>
					{[0, 1].map((row) => (
						<div key={row} className="flex items-center gap-3 px-2">
							<div className="w-16 shrink-0">
								<SkeletonLine minWidth={70} maxWidth={90} />
							</div>
							<div className="flex-1">
								<SkeletonLine minWidth={35} maxWidth={65} />
							</div>
						</div>
					))}
				</div>
			))}
		</div>
	);
}
