// parity/emdash/scheduled-publishing-source/upstream/packages/admin/src/components/calendar/CalendarToolbar.tsx
import { Button, Loader } from "@cloudflare/kumo";
import { useLingui } from "@lingui/react/macro";
import { Globe } from "@phosphor-icons/react";

import type { CalendarDisplay } from "../../lib/calendar.js";
import { CaretNext, CaretPrev } from "../ArrowIcons.js";

interface CalendarToolbarProps {
	title: string;
	display: CalendarDisplay;
	/** An instant in the shown month, for zone names that change with daylight saving time. */
	zoneTime: number;
	loading: boolean;
	onPrevious: () => void;
	onNext: () => void;
	onToday: () => void;
	/** Called when the pointer or focus reaches a month button, before it is pressed. */
	onPreviewPrevious?: () => void;
	onPreviewNext?: () => void;
}

export function CalendarToolbar({
	title,
	display,
	zoneTime,
	loading,
	onPrevious,
	onNext,
	onToday,
	onPreviewPrevious,
	onPreviewNext,
}: CalendarToolbarProps) {
	const { t } = useLingui();
	const siteZone = display.zoneShortName(zoneTime);
	const viewerZone = display.viewerZoneShortName(zoneTime);
	const showViewerZone = display.viewerZoneDiffers && viewerZone !== siteZone;
	const zoneName = display.zoneName;
	const viewerZoneName = display.viewerZoneName;
	const zoneDescription = showViewerZone
		? t`Times are in ${zoneName}. Your browser uses ${viewerZoneName}.`
		: t`Times are in ${zoneName}.`;

	return (
		<div className="flex items-start justify-between gap-4">
			<div className="flex min-w-0 flex-wrap items-baseline gap-x-4 gap-y-1">
				<h2 className="text-xl leading-7 font-semibold text-kumo-default">{title}</h2>
				<p
					title={zoneDescription}
					className="flex items-center gap-1.5 text-sm text-kumo-subtle tabular-nums"
				>
					<Globe aria-hidden="true" className="size-4 shrink-0 self-center" />
					<span aria-hidden="true">
						{showViewerZone ? t`${siteZone} · Your time: ${viewerZone}` : siteZone}
					</span>
					<span className="sr-only">{zoneDescription}</span>
				</p>
			</div>
			<div className="flex h-7 shrink-0 items-center gap-1">
				{loading && <Loader size="sm" aria-label={t`Loading`} className="me-1" />}
				<Button
					variant="ghost"
					shape="square"
					size="sm"
					aria-label={t`Previous month`}
					icon={<CaretPrev aria-hidden="true" />}
					onClick={onPrevious}
					onPointerEnter={onPreviewPrevious}
					onFocus={onPreviewPrevious}
				/>
				<Button variant="secondary" size="sm" onClick={onToday}>
					{t`Today`}
				</Button>
				<Button
					variant="ghost"
					shape="square"
					size="sm"
					aria-label={t`Next month`}
					icon={<CaretNext aria-hidden="true" />}
					onClick={onNext}
					onPointerEnter={onPreviewNext}
					onFocus={onPreviewNext}
				/>
			</div>
		</div>
	);
}

// src/lib/calendar/CalendarToolbar.svelte
<script lang="ts">
  // Source CalendarToolbar semantics with native controls and CSS.
  // EmDash1.1.0 pin913cb1bb; MIT notices/emdash-MIT.txt.
  import type { CalendarDisplay } from './calendar.ts';
  let {title,display,zoneTime,loading,onPrevious,onNext,onToday,onPreviewPrevious,onPreviewNext}:{
    title:string;display:CalendarDisplay;zoneTime:number;loading:boolean;
    onPrevious:()=>void;onNext:()=>void;onToday:()=>void;onPreviewPrevious?:()=>void;onPreviewNext?:()=>void;
  }=$props();
  const siteZone=$derived(display.zoneShortName(zoneTime)),viewerZone=$derived(display.viewerZoneShortName(zoneTime));
  const showViewerZone=$derived(display.viewerZoneDiffers&&viewerZone!==siteZone);
  const zoneDescription=$derived(showViewerZone?`Times are in ${display.zoneName}. Your browser uses ${display.viewerZoneName}.`:`Times are in ${display.zoneName}.`);
</script>
<div class="toolbar"><div><h2>{title}</h2><p title={zoneDescription}><span aria-hidden="true">{showViewerZone?`${siteZone} · Your time: ${viewerZone}`:siteZone}</span><span class="sr-only">{zoneDescription}</span></p></div><div class="month-nav">{#if loading}<span class="loader" role="img" aria-label="Loading">◌</span>{/if}<button type="button" aria-label="Previous month" onclick={onPrevious} onpointerenter={onPreviewPrevious} onfocus={onPreviewPrevious}>‹</button><button type="button" onclick={onToday}>Today</button><button type="button" aria-label="Next month" onclick={onNext} onpointerenter={onPreviewNext} onfocus={onPreviewNext}>›</button></div></div>
<style>.toolbar{display:flex;justify-content:space-between;gap:1rem;align-items:start;}h2{margin:0;font-size:1.25rem;}p{font-size:.875rem;color:var(--muted-foreground,#666);}.month-nav{display:flex;gap:.35rem;align-items:center;}button{font:inherit;color:inherit;background:var(--card,#fff);border:1px solid var(--border,#ccc);border-radius:.35rem;padding:.55rem .8rem;cursor:pointer;}button:focus-visible{outline:2px solid var(--ring,#165ccc);outline-offset:2px;}.loader{font-size:1.25rem;}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0;}</style>
