// parity/emdash/scheduled-publishing-source/upstream/packages/admin/src/components/calendar/CalendarFilters.tsx
import { Badge, Button, DropdownMenu } from "@cloudflare/kumo";
import { useLingui } from "@lingui/react/macro";
import { Check, Funnel, X } from "@phosphor-icons/react";
import type * as React from "react";

import {
	CALENDAR_STATES,
	type CalendarDisplay,
	type CalendarFilterValues,
} from "../../lib/calendar.js";
import { getLocaleLabel } from "../../locales/index.js";
import {
	CALENDAR_STATE_LABELS,
	CalendarCollectionTag,
	CalendarStateIcon,
} from "./CalendarEntry.js";

type FilterKey = keyof CalendarFilterValues;

interface CalendarFilterGroup {
	key: FilterKey;
	label: string;
	options: ReadonlyArray<{ value: string; content: React.ReactNode }>;
}

interface CalendarFiltersProps {
	display: CalendarDisplay;
	collections: ReadonlyArray<{ slug: string; label: string }>;
	/** Content locales; the locale filter shows only when there is more than one. */
	locales: readonly string[];
	value: CalendarFilterValues;
	onChange: (value: Partial<CalendarFilterValues>) => void;
	triggerRef?: React.Ref<HTMLButtonElement>;
}

const NO_FILTERS: CalendarFilterValues = { collections: [], locales: [], states: [] };

/**
 * A checkbox drawn like Kumo's, for menu items that otherwise show only a
 * check mark once chosen. It follows the item's checked state.
 */
function MenuCheckbox() {
	return (
		<span
			aria-hidden="true"
			className="flex size-4 shrink-0 items-center justify-center rounded-sm bg-kumo-base ring ring-kumo-interact transition-colors group-data-checked:bg-kumo-contrast group-data-checked:ring-kumo-contrast motion-reduce:transition-none"
		>
			<Check
				weight="bold"
				size={12}
				className="invisible text-kumo-inverse group-data-checked:visible"
			/>
		</span>
	);
}

/** One menu for every filter; an empty selection in a group means all of it. */
export function CalendarFilters({
	display,
	collections,
	locales,
	value,
	onChange,
	triggerRef,
}: CalendarFiltersProps) {
	const { t } = useLingui();
	const groups: CalendarFilterGroup[] = [
		{
			key: "collections",
			label: t`Collection`,
			options: collections.map((collection) => ({
				value: collection.slug,
				content: <CalendarCollectionTag slug={collection.slug} display={display} />,
			})),
		},
		...(locales.length > 1
			? [
					{
						key: "locales" as const,
						label: t`Locale`,
						options: locales.map((locale) => ({
							value: locale,
							content: (
								<>
									<span
										aria-hidden="true"
										className="w-7 shrink-0 rounded-sm bg-kumo-fill py-0.5 text-center text-[10px] leading-4 font-semibold tracking-wide text-kumo-subtle uppercase"
									>
										{locale}
									</span>
									<span className="truncate">{getLocaleLabel(locale)}</span>
								</>
							),
						})),
					},
				]
			: []),
		{
			key: "states",
			label: t`State`,
			options: CALENDAR_STATES.map((state) => ({
				value: state,
				content: (
					<>
						<CalendarStateIcon state={state} />
						<span className="truncate">{t(CALENDAR_STATE_LABELS[state])}</span>
					</>
				),
			})),
		},
	];
	const activeCount = value.collections.length + value.locales.length + value.states.length;

	return (
		<DropdownMenu>
			<DropdownMenu.Trigger
				render={
					<Button
						ref={triggerRef}
						variant="secondary"
						className="w-full justify-center text-sm sm:w-auto"
						icon={
							<Funnel
								aria-hidden="true"
								weight={activeCount > 0 ? "fill" : "regular"}
								className="size-4"
							/>
						}
						aria-label={activeCount > 0 ? t`Filter: ${activeCount} selected` : undefined}
					>
						{t`Filter`}
						{activeCount > 0 && (
							<Badge variant="blue" className="min-w-5 justify-center px-1 tabular-nums">
								{activeCount}
							</Badge>
						)}
					</Button>
				}
			/>
			<DropdownMenu.Content
				align="end"
				// Kumo's menu animates on Radix's data-state, which Base UI never sets, so this uses its popover transition.
				className="max-h-[min(32rem,var(--available-height))] w-[max(15rem,var(--anchor-width))] origin-(--transform-origin) overflow-y-auto transition-[transform,scale,opacity] duration-150 data-ending-style:scale-90 data-ending-style:opacity-0 data-instant:duration-0 data-starting-style:scale-90 data-starting-style:opacity-0 motion-reduce:transition-none"
			>
				{groups.map((group, index) => {
					const selected: readonly string[] = value[group.key];
					return (
						<DropdownMenu.Group key={group.key} className={index > 0 ? "mt-1" : undefined}>
							<DropdownMenu.Label className="pt-2 pb-1 text-xs text-kumo-subtle">
								{group.label}
							</DropdownMenu.Label>
							{group.options.map((option) => (
								<DropdownMenu.CheckboxItem
									key={option.value}
									checked={selected.includes(option.value)}
									closeOnClick={false}
									// Kumo's own check mark is hidden in favor of the drawn checkbox.
									className="group gap-2.5 px-2 [&>[data-checked]]:hidden"
									onCheckedChange={(checked) => {
										const next = checked
											? [...selected, option.value]
											: selected.filter((entry) => entry !== option.value);
										// Menu order keeps the URL stable however the options were picked.
										onChange({
											[group.key]: group.options
												.map((entry) => entry.value)
												.filter((entry) => next.includes(entry)),
										});
									}}
								>
									<MenuCheckbox />
									<span className="flex min-w-0 items-center gap-2">{option.content}</span>
								</DropdownMenu.CheckboxItem>
							))}
						</DropdownMenu.Group>
					);
				})}
				{activeCount > 0 && (
					<>
						<DropdownMenu.Separator />
						<DropdownMenu.Item
							icon={<X aria-hidden="true" className="size-4" />}
							className="gap-2.5 data-highlighted:bg-kumo-tint"
							onClick={() => onChange(NO_FILTERS)}
						>
							{t`Clear filters`}
						</DropdownMenu.Item>
					</>
				)}
			</DropdownMenu.Content>
		</DropdownMenu>
	);
}

// src/lib/calendar/CalendarFilters.svelte
<script lang="ts">
  // EmDash1.1.0 CalendarFilters selection/order contracts, pin913cb1bb; MIT.
  import { CALENDAR_STATES, type CalendarDisplay, type CalendarFilterValues } from './calendar.ts';
  import { stateLabels } from './entry.ts';
  let { display, collections, locales, value, onChange, triggerRef }: {
    display:CalendarDisplay; collections:{slug:string;label:string}[]; locales:readonly string[];
    value:CalendarFilterValues; onChange:(value:Partial<CalendarFilterValues>)=>void;
    triggerRef?:{current:HTMLButtonElement|null};
  } = $props();
  let open=$state(false), trigger=$state<HTMLButtonElement>();
  const count=$derived(value.collections.length+value.locales.length+value.states.length);
  const groups=$derived([{key:'collections' as const,label:'Collection',options:collections.map(c=>({value:c.slug,label:c.label}))},
    ...(locales.length>1?[{key:'locales' as const,label:'Locale',options:locales.map(locale=>({value:locale,label:new Intl.DisplayNames([display.locale],{type:'language'}).of(locale)??locale}))}]:[]),
    {key:'states' as const,label:'State',options:CALENDAR_STATES.map(state=>({value:state,label:stateLabels[state]}))}]);
  $effect(()=>{if(triggerRef)triggerRef.current=trigger??null;});
  function toggle(key:keyof CalendarFilterValues, selected:string, options:{value:string}[]) {
    const previous:readonly string[]=value[key];
    const next=previous.includes(selected)?previous.filter(v=>v!==selected):[...previous,selected];
    onChange({[key]:options.map(v=>v.value).filter(v=>next.includes(v))});
  }
</script>
<div class="filter"><button type="button" bind:this={trigger} aria-haspopup="menu" aria-expanded={open} aria-label={count?`Filter: ${count} selected`:undefined} onclick={()=>open=!open}>Filter {#if count}<span>{count}</span>{/if}</button>
{#if open}<div role="menu" aria-label="Calendar filters" onkeydown={event=>{if(event.key==='Escape'){open=false;trigger?.focus();}}} tabindex="-1">
  {#each groups as group}<div role="group" aria-label={group.label}><h3>{group.label}</h3>
  {#each group.options as option}<button type="button" role="menuitemcheckbox" aria-checked={(value[group.key] as readonly string[]).includes(option.value)} onclick={()=>toggle(group.key,option.value,group.options)}>{option.label}</button>{/each}</div>{/each}
  {#if count}<button type="button" role="menuitem" onclick={()=>{onChange({collections:[],locales:[],states:[]});open=false;trigger?.focus();}}>Clear filters</button>{/if}
</div>{/if}</div>
<style>.filter{position:relative;}button{font:inherit;padding:.55rem .8rem;border:1px solid var(--border,#ccc);border-radius:.35rem;background:var(--card,#fff);color:inherit;cursor:pointer;}[role="menu"]{position:absolute;right:0;top:calc(100% + .35rem);z-index:30;min-width:15rem;max-height:32rem;overflow:auto;padding:.5rem;background:var(--card,#fff);border:1px solid var(--border,#ccc);box-shadow:0 8px 24px #0002;}[role="menu"] button{display:block;width:100%;text-align:left;border:0;}[aria-checked="true"]::before{content:'✓ ';}h3{font-size:.7rem;text-transform:uppercase;opacity:.65;margin:.5rem;}button:focus-visible{outline:2px solid var(--ring,#165ccc);}</style>
